-- Compás Academy · Profundización pedagógica de Nivel 2
-- Mantiene el curso en draft y amplía las 18 lecciones con método, caso, ejercicio y registro operativo.

do $m$
declare
  v_course uuid;
  item jsonb;
  lessons jsonb := $j$
  [
    {"m":1,"l":1,"minutes":20,"objective":"Elegir un mercado concreto antes de iniciar actividad comercial.","core":"Prospectar sin enfoque produce conversaciones poco relevantes y hace difícil aprender de los resultados. Un mercado útil combina cercanía, necesidad observable y posibilidad real de llegar a quien decide.","method":"Trabaja con tres filtros: acceso, problema probable y capacidad de acción. Prioriza uno o dos segmentos durante un ciclo de 30 días y evita cambiar de mercado después de pocos intentos.","case":"Una manicurista con agenda irregular y seguimiento manual puede ser más accionable que un negocio grande al que no tienes acceso. La oportunidad no depende solo del tamaño, sino de la claridad del problema y de la posibilidad de conversar.","practice":"Elige dos segmentos, escribe por qué podrían necesitar Compás y define qué señal observable confirmarías antes de contactarlos.","metric":"Segmento, fuente del prospecto, señal observada y fecha del primer contacto."},
    {"m":1,"l":2,"minutes":22,"objective":"Construir un perfil de cliente ideal que ayude a priorizar, no a excluir de forma automática.","core":"El cliente ideal Compás tiene una necesidad que podemos ayudar a ordenar, disposición para implementar y un nivel de complejidad compatible con el alcance disponible. El perfil sirve para priorizar esfuerzo, no para inventar necesidades.","method":"Evalúa cinco señales: actividad comercial existente, desorden de seguimiento, intención de crecer, acceso a decisión y capacidad para empezar con un nivel realista.","case":"Dos negocios reciben 30 consultas al mes. Uno ya tiene CRM y seguimiento disciplinado; el otro pierde conversaciones en WhatsApp. Aunque ambos generan leads, el segundo presenta una brecha más clara para una solución inicial.","practice":"Describe un cliente ideal y un cliente no prioritario. Explica qué evidencia usarías para diferenciarlos.","metric":"Necesidad principal, nivel de urgencia, capacidad estimada y persona decisora."},
    {"m":1,"l":3,"minutes":25,"objective":"Convertir el mercado elegido en una lista de trabajo priorizada de 50 prospectos.","core":"Una lista útil no es una colección de nombres. Cada registro debe permitir saber por qué vale la pena contactar, qué canal utilizar y cuál es el siguiente paso.","method":"Divide 50 prospectos en A, B y C. A: necesidad visible y acceso alto. B: necesidad probable o acceso medio. C: exploratorios. Empieza por A y revisa la clasificación con evidencia nueva.","case":"Si detectas un negocio con formulario activo pero respuestas tardías, registra esa observación. El primer mensaje puede partir de ella en lugar de usar una apertura genérica.","practice":"Construye tus primeros 15 prospectos con nombre, canal, observación, prioridad y fecha de acción; completa 50 durante la semana.","metric":"Nombre, contacto, prioridad A/B/C, origen, observación, próximo paso y fecha."},
    {"m":2,"l":1,"minutes":22,"objective":"Usar relaciones y referidos de forma profesional sin deteriorar vínculos personales.","core":"La red personal funciona mejor cuando se pide contexto o una presentación, no cuando se convierte a cada conocido en comprador. Un referido de calidad reduce fricción porque llega con confianza transferida.","method":"Explica en una frase a quién ayudas, menciona una situación concreta y pide una introducción solo si la persona conoce a alguien con esa necesidad.","case":"En vez de decir ‘vendo sistemas para negocios’, puedes explicar que ayudas a negocios que reciben consultas pero pierden seguimiento y preguntar si conocen a alguien viviendo esa situación.","practice":"Redacta dos solicitudes de referido: una para un contacto cercano y otra para un cliente o aliado profesional.","metric":"Quién refiere, prospecto referido, contexto, fecha de presentación y resultado."},
    {"m":2,"l":2,"minutes":24,"objective":"Prospectar en redes sociales a partir de señales reales y comunicación personalizada.","core":"Las redes permiten observar cómo capta y atiende un negocio. El objetivo no es auditar públicamente ni criticar, sino detectar una posible oportunidad y pedir permiso para conversar.","method":"Observa perfil, llamada a la acción, enlaces, respuesta visible y consistencia. Formula una observación específica, reconoce que puede faltarte contexto y termina con una pregunta breve.","case":"Un perfil publica promociones pero no tiene enlace claro para agendar. Puedes preguntar cómo están convirtiendo esas consultas en citas antes de sugerir una solución.","practice":"Selecciona cinco negocios, identifica una señal verificable y escribe un mensaje C-O-P: contexto, observación y pregunta.","metric":"Red social, señal detectada, mensaje enviado, respuesta y siguiente acción."},
    {"m":2,"l":3,"minutes":23,"objective":"Crear oportunidades mediante presencia local y alianzas complementarias.","core":"Los aliados correctos atienden al mismo mercado desde otra necesidad y pueden intercambiar contexto comercial sin competir directamente. Toda alianza debe respetar condiciones autorizadas y protección de datos.","method":"Mapea profesionales complementarios, define el beneficio mutuo y establece una forma simple de referencia. No prometas comisiones, descuentos o exclusividad fuera de las reglas aprobadas.","case":"Un contador que atiende micronegocios puede detectar clientes con operación desordenada; un Freelance Compás puede detectar clientes que necesitan apoyo fiscal. La relación funciona si ambos entienden cuándo referir.","practice":"Identifica cinco posibles aliados locales y prepara una propuesta de colaboración de tres frases sin ofrecer condiciones no autorizadas.","metric":"Aliado, tipo de relación, prospectos referidos, responsable y seguimiento."},
    {"m":3,"l":1,"minutes":20,"objective":"Abrir conversaciones con mensajes breves que generen permiso para continuar.","core":"El primer contacto no necesita explicar todo Compás. Su función es ganar atención suficiente para una conversación y demostrar que el mensaje tiene contexto.","method":"Usa C-O-P: contexto real, observación verificable y pregunta sencilla. Evita archivos, listas de funciones, precios y párrafos largos en la primera interacción.","case":"‘Vi que reciben solicitudes por Instagram y WhatsApp. ¿Cómo están dando seguimiento cuando varias personas escriben al mismo tiempo?’ abre diagnóstico; ‘te vendo un CRM’ lo cierra antes de entender.","practice":"Escribe tres aperturas para tres sectores diferentes y reduce cada una hasta que pueda leerse en menos de 20 segundos.","metric":"Canal, mensaje inicial, respuesta, permiso para continuar y fecha."},
    {"m":3,"l":2,"minutes":21,"objective":"Despertar interés con observaciones útiles sin asumir pérdidas o problemas no confirmados.","core":"Una buena observación señala una situación visible y permite que el prospecto confirme o corrija. La curiosidad es más efectiva que diagnosticar desde fuera.","method":"Describe lo que viste, explica por qué te llamó la atención y pregunta cómo lo resuelven actualmente. Nunca afirmes cuánto dinero pierden sin datos del cliente.","case":"Si un sitio no tiene un llamado claro a WhatsApp, pregunta cómo llegan las consultas al equipo. Tal vez usan otro canal que no es visible y la supuesta falla no existe.","practice":"Convierte cinco críticas comunes (‘tu página está mal’) en observaciones neutrales acompañadas de una pregunta.","metric":"Observación, respuesta del prospecto, necesidad confirmada o descartada."},
    {"m":3,"l":3,"minutes":21,"objective":"Aplicar una cadencia de seguimiento persistente pero respetuosa.","core":"Dar seguimiento no significa repetir ‘¿viste mi mensaje?’. Cada contacto debe aportar contexto, una pregunta o una razón válida para retomar. La solicitud de no contacto siempre detiene la secuencia.","method":"Usa una cadencia corta con variación de valor: apertura, recordatorio contextual, recurso/idea y cierre amable. Espacia los contactos y registra el resultado.","case":"Después de una observación sobre agenda, el segundo mensaje puede preguntar si el problema aparece en horas pico; el tercero puede ofrecer mostrar un flujo sencillo. Si no hay respuesta, cierra la secuencia sin presión.","practice":"Diseña una secuencia de cuatro contactos para un prospecto real, incluyendo el mensaje con el que cerrarías el ciclo.","metric":"Número de intento, fecha, canal, contenido, respuesta y estado de contacto."},
    {"m":4,"l":1,"minutes":26,"objective":"Conducir un diagnóstico que descubra proceso actual, cuello de botella e impacto.","core":"El diagnóstico evita vender por intuición. Debe entender cómo llega una oportunidad, quién responde, qué ocurre después y dónde se pierde continuidad.","method":"Pregunta en cuatro bloques: captación, seguimiento, operación y objetivo. Profundiza con ‘¿qué pasa después?’ y cuantifica solo con datos que el prospecto pueda sostener.","case":"Un negocio cree necesitar publicidad, pero al revisar descubre que ya recibe suficientes consultas y que el problema es responder tarde. La recomendación cambia de ‘más leads’ a ‘mejor seguimiento’.","practice":"Realiza un diagnóstico de práctica de 10 preguntas y resume el problema en una frase que el prospecto reconocería como propia.","metric":"Proceso actual, cuello de botella, impacto, objetivo y evidencia aportada por el cliente."},
    {"m":4,"l":2,"minutes":24,"objective":"Calificar oportunidades usando dolor, urgencia, capacidad y decisión.","core":"No toda necesidad debe convertirse inmediatamente en propuesta. Calificar protege al prospecto y al Freelance de invertir tiempo en una oportunidad que aún no puede avanzar.","method":"Asigna una señal baja/media/alta a cuatro dimensiones: dolor relevante, urgencia temporal, capacidad de implementación/pago y acceso a decisión. Usa el resultado para definir siguiente paso, no para manipular.","case":"Un negocio reconoce el problema y tiene presupuesto, pero la decisión depende de un socio que no participa. Antes de cotizar, conviene incorporar a quien decide.","practice":"Califica tres oportunidades actuales y escribe qué condición falta para que cada una avance.","metric":"Dolor, urgencia, capacidad, decisión, bloqueo principal y próximo paso."},
    {"m":4,"l":3,"minutes":25,"objective":"Recomendar el nivel mínimo útil de Crece con Compás según el diagnóstico.","core":"La recomendación correcta resuelve la necesidad prioritaria sin cargar al cliente con herramientas que todavía no utilizará. El crecimiento posterior debe responder a uso y necesidad real.","method":"Relaciona necesidad con alcance: Inicio para presencia y seguimiento esencial; Impulso para organización comercial; Crece para automatización y operación más avanzada; Negocio para mayor capacidad. Lo no estándar se cotiza aparte.","case":"Una emprendedora con pocas consultas y sin CRM probablemente necesita Inicio o Impulso; una empresa con pipeline, pagos y varios flujos puede requerir Crece o Negocio.","practice":"Toma cuatro casos y justifica plan recomendado, plan que sería excesivo y señal que justificaría subir de nivel.","metric":"Necesidad, plan recomendado, razón, alcance especial y siguiente paso."},
    {"m":5,"l":1,"minutes":23,"objective":"Presentar una propuesta conectando problema, resultado operativo y alcance antes del precio.","core":"El valor no se construye enumerando funciones. Se construye mostrando cómo el alcance cambia el proceso que el prospecto describió durante el diagnóstico.","method":"Presenta en cuatro pasos: ‘hoy ocurre’, ‘queremos pasar a’, ‘para hacerlo propongo’, ‘el siguiente paso es’. Después muestra precio y límites del alcance.","case":"En lugar de ‘incluye CRM y automatización’, explica: ‘hoy las consultas quedan repartidas; centralizaremos contactos, próximos pasos y recordatorios para que el equipo sepa qué atender’.","practice":"Graba o escribe una presentación de 90 segundos para una oportunidad real y elimina toda función que no se conecte con una necesidad confirmada.","metric":"Problema resumido, solución propuesta, alcance, precio presentado y reacción."},
    {"m":5,"l":2,"minutes":27,"objective":"Explorar objeciones para responder a la preocupación real y no a la frase superficial.","core":"‘Está caro’, ‘lo voy a pensar’ o ‘ya tengo algo’ no son respuestas finales: son puertas para entender comparación, riesgo, prioridad o falta de claridad. La objeción se investiga antes de rebatir.","method":"Usa E-C-R: escuchar, clarificar, responder. Repite la preocupación con tus palabras, pregunta qué la origina y responde únicamente con información autorizada.","case":"Ante ‘está caro’, preguntar ‘¿con qué lo estás comparando o qué presupuesto tenías previsto?’ diferencia un problema de presupuesto de una falta de valor percibido.","practice":"Practica respuestas a precio, tiempo, competidor, desconfianza y ‘lo voy a pensar’. Incluye una pregunta de clarificación en cada caso.","metric":"Objeción, causa detectada, respuesta, condición para avanzar y fecha de seguimiento."},
    {"m":5,"l":3,"minutes":23,"objective":"Cerrar conversaciones con una decisión o acción concreta sin presión indebida.","core":"Cerrar no siempre significa cobrar en ese momento. También puede ser agendar a la persona decisora, confirmar una prueba, enviar contrato o establecer una fecha de decisión.","method":"Resume acuerdos, valida que no exista una duda pendiente y plantea una siguiente acción específica con responsable y fecha. Si el prospecto dice no, registra el motivo con respeto.","case":"‘Si el alcance te hace sentido, el siguiente paso es generar la propuesta formal y revisar activación el martes. ¿Avanzamos así?’ es más claro que ‘avísame cualquier cosa’.","practice":"Define tres cierres: compra, reunión con decisor y seguimiento futuro. Evita urgencias inventadas.","metric":"Resultado, acción acordada, responsable, fecha y motivo de pérdida si aplica."},
    {"m":6,"l":1,"minutes":25,"objective":"Usar el pipeline de Compás One como representación fiel del trabajo comercial.","core":"El pipeline solo sirve si refleja la realidad. Mover oportunidades para mejorar métricas destruye la capacidad del Coach y del equipo de detectar dónde existe fricción.","method":"Actualiza etapa cuando ocurre un evento real, conserva un próximo paso en toda oportunidad abierta y registra actividad relevante. Revisa diariamente vencidos y oportunidades sin movimiento.","case":"Una propuesta enviada no es negociación si el cliente todavía no la revisó. Mantenerla en propuesta permite medir con precisión dónde se atascan las ventas.","practice":"Audita tu pipeline: corrige etapas, agrega próximo paso y fecha a cada oportunidad abierta y cierra registros que ya no deben seguir activos.","metric":"Etapa real, último contacto, próximo paso, fecha, valor estimado y motivo de estancamiento."},
    {"m":6,"l":2,"minutes":23,"objective":"Dar seguimiento a propuestas con contexto y acuerdos, no con recordatorios vacíos.","core":"Una propuesta pierde impulso cuando no existe razón para retomarla. El seguimiento debe volver a la necesidad, resolver una duda o confirmar el acuerdo de decisión.","method":"Antes de escribir, revisa la última conversación. Retoma el punto pendiente y formula una pregunta que permita decidir. Si hubo una fecha acordada, respétala.","case":"‘La última vez quedamos en revisar quién operaría el seguimiento. ¿Pudieron definirlo?’ aporta contexto; ‘solo paso a preguntar’ no agrega información.","practice":"Reescribe tres seguimientos genéricos usando contexto, pregunta y siguiente paso.","metric":"Fecha prometida, tema pendiente, respuesta, nueva fecha y etapa."},
    {"m":6,"l":3,"minutes":28,"objective":"Interpretar KPIs semanales para decidir qué habilidad o actividad mejorar.","core":"Una métrica aislada no explica un problema. La historia aparece al comparar volumen y conversiones entre etapas: poca prospección, baja respuesta, diagnóstico débil, propuestas insuficientes o cierres bajos requieren acciones distintas.","method":"Revisa actividad y conversión en orden: prospectos → contactados → diagnóstico → propuesta → ganado. Identifica el cuello de botella mayor y elige una sola mejora principal para la siguiente semana.","case":"Si hay 50 prospectos y 30 contactos pero solo 3 diagnósticos, aumentar otros 50 prospectos no resuelve el cuello de botella; primero conviene mejorar apertura y calificación.","practice":"Calcula tu embudo de los últimos 30 días, identifica la caída principal y define una hipótesis y una acción medible para siete días.","metric":"Volumen por etapa, conversiones, seguimientos vencidos, hipótesis de mejora y acción semanal."}
  ]$j$::jsonb;
begin
  select id into v_course
  from public.courses
  where slug='nivel-2-captacion-y-ventas-compas'
  limit 1;

  if v_course is null then
    raise exception 'Nivel 2 course is required';
  end if;

  if exists(select 1 from public.courses where id=v_course and status<>'draft') then
    raise exception 'Nivel 2 must remain draft while enriching lesson content';
  end if;

  for item in select value from jsonb_array_elements(lessons) loop
    update public.lessons l
    set content_html=
      '<h2>'||l.title||'</h2>'||
      '<p><strong>Objetivo:</strong> '||(item->>'objective')||'</p>'||
      '<h3>Idea central</h3><p>'||(item->>'core')||'</p>'||
      '<h3>Método de trabajo</h3><p>'||(item->>'method')||'</p>'||
      '<h3>Caso práctico</h3><p>'||(item->>'case')||'</p>'||
      '<h3>Ejercicio aplicado</h3><p>'||(item->>'practice')||'</p>'||
      '<h3>Qué registrar en Compás One</h3><p>'||(item->>'metric')||'</p>'||
      '<blockquote>La calidad comercial mejora cuando cada aprendizaje termina en una acción observable y un próximo paso con fecha.</blockquote>',
        duration_minutes=(item->>'minutes')::int,
        updated_at=now()
    from public.modules m
    where l.module_id=m.id
      and m.course_id=v_course
      and m.position=(item->>'m')::int
      and l.position=(item->>'l')::int;

    if not found then
      raise exception 'Missing Nivel 2 lesson at module %, lesson %',item->>'m',item->>'l';
    end if;
  end loop;

  update public.courses
  set duration_label='6–7 h',
      description='Ruta práctica y aplicada para convertir mercado, captación, diagnóstico, propuesta, cierre y seguimiento en un proceso comercial medible dentro de Compás One.',
      updated_at=now()
  where id=v_course;
end $m$;
