-- Compás Academy · Nivel 4 · Evaluación formativa Módulo 1
-- 12 reactivos; aprobación recomendada 80% (10/12).
-- Banco declarativo para carga/QA; no emite certificación.

create table if not exists public.academy_level4_question_bank (
  id bigint generated by default as identity primary key,
  module_position int not null,
  question_position int not null,
  prompt text not null,
  options jsonb not null,
  correct_option text not null check (correct_option in ('A','B','C','D')),
  rationale text not null,
  unique(module_position,question_position)
);

alter table public.academy_level4_question_bank enable row level security;
revoke all on public.academy_level4_question_bank from anon, authenticated;

do $m$
declare q jsonb;
begin
  for q in select * from jsonb_array_elements($j$[
 {"n":1,"q":"¿Cuál describe mejor el cambio central al pasar de agente a supervisor?","o":{"A":"Resolver personalmente las oportunidades difíciles","B":"Construir claridad y capacidad para que otros ejecuten","C":"Enviar más mensajes que el equipo","D":"Autorizar descuentos para cerrar rápido"},"a":"B","r":"La supervisión crea capacidad y sistema; rescatar todo genera dependencia."},
 {"n":2,"q":"Un agente pide que el supervisor tome una llamada compleja. ¿Qué acción aplica mejor HABILITA?","o":{"A":"Tomar la llamada inmediatamente","B":"Ignorar la solicitud","C":"Revisar diagnóstico, preparar rutas y observar al agente ejecutar","D":"Transferirla a otro agente sin explicación"},"a":"C","r":"El supervisor brinda contexto y coaching sin sustituir automáticamente al responsable."},
 {"n":3,"q":"¿Cuál es un riesgo de que el supervisor rescate cada oportunidad?","o":{"A":"Aumentar la autonomía","B":"Crear dependencia y cuello de botella","C":"Mejorar la documentación","D":"Reducir la necesidad de liderazgo"},"a":"B","r":"El rescate recurrente impide desarrollar criterio y concentra la operación."},
 {"n":4,"q":"¿Qué elemento NO pertenece a un estándar CAFE?","o":{"A":"Conducta","B":"Artefacto o evidencia","C":"Frecuencia","D":"Entusiasmo percibido"},"a":"D","r":"CAFE exige elementos verificables, no impresiones vagas."},
 {"n":5,"q":"¿Cuál frase es un estándar más verificable?","o":{"A":"Da mejor seguimiento","B":"Échale ganas","C":"Toda oportunidad activa tiene siguiente paso registrado","D":"Sé excelente con los clientes"},"a":"C","r":"Describe una conducta observable y comprobable."},
 {"n":6,"q":"Dos agentes venden poco; uno documenta correctamente y otro abandona seguimientos. ¿Qué debe hacer el supervisor?","o":{"A":"Aplicar la misma corrección a ambos","B":"Distinguir problema de conversión de problema de disciplina","C":"Despedir a ambos","D":"Prometerles más leads"},"a":"B","r":"Resultados similares pueden provenir de causas controlables distintas."},
 {"n":7,"q":"¿Por qué conviene gestionar conductas controlables además de ventas finales?","o":{"A":"Porque las ventas nunca importan","B":"Porque el resultado final también depende de factores externos","C":"Porque evita usar CRM","D":"Porque elimina la necesidad de métricas"},"a":"B","r":"El liderazgo debe observar resultados y las conductas que el equipo sí puede ejecutar."},
 {"n":8,"q":"¿Cuál combinación representa el Ritmo 4R?","o":{"A":"Radar, Revisión, Retroalimentación, Resumen","B":"Registro, Rebaja, Referido, Renovación","C":"Reclutamiento, Ranking, Recompensa, Rotación","D":"Resultado, Reacción, Repetición, Reemplazo"},"a":"A","r":"Es la cadencia definida para supervisar sin microgestión."},
 {"n":9,"q":"¿Qué debería terminar toda reunión de supervisión?","o":{"A":"Una frase motivacional","B":"Más reuniones","C":"Responsable, fecha y evidencia esperada","D":"Una venta asegurada"},"a":"C","r":"Los acuerdos deben convertirse en compromisos verificables."},
 {"n":10,"q":"¿Qué situación justifica romper la cadencia normal e intervenir antes?","o":{"A":"El agente tarda unos minutos en responder al supervisor","B":"Existe riesgo de cliente, cumplimiento o reputación","C":"El supervisor quiere revisar todo","D":"No hay novedades"},"a":"B","r":"Los riesgos relevantes requieren intervención o escalamiento oportuno."},
 {"n":11,"q":"¿Cuál es un ejemplo de microgestión?","o":{"A":"Revisar excepciones críticas diariamente","B":"Tener un 1:1 breve de coaching","C":"Preguntar cada dos horas cuántos mensajes envió cada agente","D":"Revisar pipeline semanalmente"},"a":"C","r":"La vigilancia continua de actividad sin propósito consume atención y crea dependencia."},
 {"n":12,"q":"Antes de intervenir en el trabajo de un agente, el supervisor debería identificar principalmente si necesita...","o":{"A":"una decisión, una habilidad o claridad","B":"un descuento","C":"más presión","D":"otra cuenta"},"a":"A","r":"Diagnosticar la necesidad permite intervenir con la intensidad correcta."}
]$j$::jsonb) loop
    insert into public.academy_level4_question_bank(module_position,question_position,prompt,options,correct_option,rationale)
    values(1,(q->>'n')::int,q->>'q',q->'o',q->>'a',q->>'r')
    on conflict(module_position,question_position) do update set prompt=excluded.prompt,options=excluded.options,correct_option=excluded.correct_option,rationale=excluded.rationale;
  end loop;
end $m$;

-- QA esperado: 12 preguntas, 48 opciones, 12 respuestas correctas; aprobación 80% => mínimo 10 correctas.