-- Compás Academy · Nivel 4 · Módulo 2 · Coaching comercial basado en evidencia
-- Amplía el curso draft; no publica Nivel 4 ni emite certificados.

do $m$
declare
  v_course uuid;
  v_module uuid;
  jl jsonb;
  lessons jsonb := $j$[
    {"p":1,"t":"Diagnosticar desempeño antes de corregir","d":"Separa síntomas, causas y evidencia para elegir una intervención de coaching útil.","m":32,"objective":"Al terminar, el supervisor podrá diagnosticar una brecha comercial distinguiendo volumen, habilidad, proceso y contexto antes de prescribir una solución.","core":"Un KPI bajo es una señal, no un diagnóstico. Si baja la conversión, la causa puede estar en calidad del lead, apertura, diagnóstico, propuesta, seguimiento o disciplina de registro. Corregir sin evidencia crea ruido y puede castigar a la persona equivocada.","method":"Marco DATO: Definir el resultado observado; Abrir la evidencia por etapa; Trazar hipótesis controlables; Ordenar una prueba de mejora. Se elige una hipótesis principal por ciclo corto y se define qué dato confirmará o descartará la causa.","case":"Una agente tiene pocas ventas. El volumen de contactos es suficiente, pero casi ninguna conversación llega a diagnóstico. En vez de pedirle ‘más actividad’, el supervisor revisa aperturas y descubre que presenta el producto antes de preguntar. La intervención cambia de volumen a habilidad de conversación.","practice":"Toma un KPI comercial bajo y construye tres hipótesis posibles. Para cada una escribe la evidencia que necesitarías y selecciona una prueba de siete días.","platform":"Usar datos reales de pipeline, actividades y próximos pasos de Compás One cuando existan. Registrar hipótesis de coaching y métrica de comprobación sin alterar etapas para mejorar artificialmente el tablero.","video":"Abrir con la frase: un número rojo no te dice qué enseñar. Mostrar un embudo con la misma venta final pero tres causas distintas. Explicar DATO paso a paso. Resolver el caso de una agente con baja llegada a diagnóstico. Cerrar: diagnostica la brecha antes de entrenar la habilidad."},
    {"p":2,"t":"Conversaciones 1:1 que producen mejora","d":"Convierte el 1:1 en una conversación de aprendizaje, compromiso y seguimiento, no en un interrogatorio de resultados.","m":34,"objective":"Conducir un 1:1 breve donde el agente interprete evidencia, identifique una mejora y salga con una práctica observable.","core":"El 1:1 no sustituye la revisión de pipeline. Su propósito es desarrollar criterio y habilidad. El supervisor llega con evidencia, escucha la lectura del agente y evita monopolizar la conversación. Un buen 1:1 termina con una conducta específica para practicar y una fecha para revisar evidencia.","method":"Marco CRECE: Contexto y objetivo; Revisar evidencia; Escuchar autodiagnóstico; Construir una alternativa; Ejecutar una práctica; Establecer seguimiento. La pregunta central es ‘¿qué harías diferente en la siguiente oportunidad y cómo lo veremos?’.","case":"Un agente pierde propuestas después de enviarlas. En el 1:1 descubre que no acuerda fecha de decisión. Practican una frase de cierre, definen usarla en cinco oportunidades y revisarán cuántas terminan con próximo paso fechado.","practice":"Diseña una agenda de 20 minutos para un 1:1 usando CRECE. Incluye tres preguntas abiertas, una práctica y una evidencia para la siguiente revisión.","platform":"Crear una tarea de desarrollo vinculada al agente con habilidad, práctica, fecha y evidencia esperada. No documentar juicios personales ni información sensible innecesaria.","video":"Contrastar un 1:1 de regaño con uno de aprendizaje. Presentar CRECE. Modelar preguntas de autodiagnóstico y una práctica corta. Mostrar cómo cerrar con evidencia y fecha. Cierre: el agente debe salir sabiendo exactamente qué probar, no solo que debe mejorar."},
    {"p":3,"t":"Observar, retroalimentar y acordar un plan de mejora","d":"Usa muestras reales de trabajo para entregar feedback específico y construir planes cortos de mejora cuando una brecha persiste.","m":36,"objective":"Dar retroalimentación sobre conducta observable, practicar una alternativa y definir un plan de mejora proporcional cuando el coaching normal no corrige la brecha.","core":"El feedback útil describe una conducta y su efecto, no etiqueta a la persona. Una sola llamada o chat tampoco representa todo el desempeño: se buscan patrones en muestras suficientes. Si la brecha persiste después de claridad, práctica y seguimiento, el supervisor formaliza un plan con expectativa, soporte, evidencia, fecha y criterio de revisión.","method":"Marco VELO: Ver evidencia; Explicar impacto; Lanzar alternativa; Observar nueva ejecución. Para un plan persistente usa PACTO: Problema observable; Acción esperada; Coaching/soporte; Tiempo de revisión; Outcome o criterio verificable.","case":"En varias conversaciones un agente responde objeciones de precio sin clarificar. El supervisor muestra dos ejemplos, explica el efecto, practica E-C-R y observa una simulación. Si tras ciclos acordados el patrón continúa, documenta PACTO con cinco conversaciones revisables y fecha de evaluación.","practice":"Analiza tres fragmentos de conversación propios o simulados. Escribe feedback VELO sin adjetivos personales y diseña un PACTO para una brecha repetida, incluyendo soporte que ofrecerá el supervisor.","platform":"Adjuntar o referenciar evidencia autorizada, registrar el compromiso y la fecha de revisión. Respetar privacidad y políticas internas; no copiar datos sensibles del cliente en notas de coaching.","video":"Mostrar feedback vago frente a feedback basado en evidencia. Recorrer VELO con una objeción de precio. Explicar cuándo el coaching normal pasa a PACTO y por qué el plan también obliga al supervisor a brindar soporte. Cerrar con la regla: conducta, impacto, alternativa, práctica y revisión."}
  ]$j$::jsonb;
begin
  select id into v_course from public.courses where slug='nivel-4-liderazgo-supervision-comercial' limit 1;
  if v_course is null then raise exception 'Nivel 4 course is required'; end if;
  if exists(select 1 from public.courses where id=v_course and status<>'draft') then raise exception 'Nivel 4 must remain draft'; end if;

  select id into v_module from public.modules where course_id=v_course and position=2 limit 1;
  if v_module is null then
    insert into public.modules(course_id,title,description,position)
    values(v_course,'2. Coaching comercial basado en evidencia','Diagnostica brechas, conduce 1:1, observa trabajo real y convierte feedback en práctica y mejora verificable.',2)
    returning id into v_module;
  else
    update public.modules set title='2. Coaching comercial basado en evidencia',description='Diagnostica brechas, conduce 1:1, observa trabajo real y convierte feedback en práctica y mejora verificable.' where id=v_module;
  end if;

  for jl in select * from jsonb_array_elements(lessons) loop
    if exists(select 1 from public.lessons where module_id=v_module and position=(jl->>'p')::int) then
      update public.lessons set title=jl->>'t',description=jl->>'d',duration_minutes=(jl->>'m')::int,content=jsonb_build_object('objective',jl->>'objective','core',jl->>'core','method',jl->>'method','case',jl->>'case','practice',jl->>'practice','platform',jl->>'platform','video',jl->>'video') where module_id=v_module and position=(jl->>'p')::int;
    else
      insert into public.lessons(module_id,title,description,position,duration_minutes,content)
      values(v_module,jl->>'t',jl->>'d',(jl->>'p')::int,(jl->>'m')::int,jsonb_build_object('objective',jl->>'objective','core',jl->>'core','method',jl->>'method','case',jl->>'case','practice',jl->>'practice','platform',jl->>'platform','video',jl->>'video'));
    end if;
  end loop;
end $m$;
