-- Compás Academy · Nivel 4 · Módulo 3 · Dirección por KPIs y decisiones de equipo
-- Amplía el curso draft; no publica Nivel 4 ni emite certificados.

do $m$
declare
  v_course uuid;
  v_module uuid;
  jl jsonb;
  lessons jsonb := $j$[
    {"p":1,"t":"Leer el embudo del equipo y detectar el cuello de botella","d":"Convierte los KPIs del equipo en un mapa de etapas para distinguir volumen, conversión, velocidad y calidad antes de intervenir.","m":35,"objective":"Al terminar, el supervisor podrá leer el embudo comercial del equipo, identificar la etapa que limita el resultado y separar problemas de volumen de problemas de conversión o seguimiento.","core":"Un tablero útil no dice solamente cuánto vendió el equipo: muestra dónde se transforma o se pierde la oportunidad. El supervisor compara entradas, avances, conversiones y tiempos por etapa. Una caída de ventas puede originarse en poca prospección, baja respuesta, diagnósticos débiles, propuestas insuficientes, falta de seguimiento o cartera estancada. La intervención correcta empieza en la primera ruptura comprobable del flujo.","method":"Marco FARO: Flujo total de oportunidades; Avance entre etapas; Ritmo o tiempo de permanencia; Origen y calidad de la oportunidad. Primero se localiza la primera etapa anormal, luego se compara con periodos y agentes equivalentes, y finalmente se formula una hipótesis operativa que pueda comprobarse sin maquillar el pipeline.","case":"Un equipo cae 20% en cierres. El supervisor observa que contactos y diagnósticos permanecen estables, pero las propuestas bajaron. Al revisar descubre que varios diagnósticos terminan sin recomendación ni fecha. La acción no es exigir más prospectos, sino fortalecer traducción de diagnóstico a propuesta y revisar cinco oportunidades por agente.","practice":"Dibuja un embudo con seis etapas y coloca volumen, conversión y tiempo promedio. Marca la primera anomalía y escribe dos hipótesis, la evidencia necesaria y una intervención de siete días.","platform":"Usar dashboard, pipeline y actividades reales de Compás One. No mover oportunidades de etapa para mejorar métricas. Registrar la hipótesis, responsable, periodo de observación y criterio de éxito.","video":"Abrir con dos equipos que venden lo mismo pero fallan en etapas distintas. Explicar por qué el total de ventas no diagnostica. Presentar FARO sobre un embudo visual. Resolver el caso de caída en propuestas. Cerrar: dirige la primera ruptura del flujo, no el número final."},
    {"p":2,"t":"Capacidad, carga y prioridades semanales del equipo","d":"Equilibra oportunidades, seguimiento y tiempo disponible para evitar saturación, abandono de cartera o actividad sin foco.","m":36,"objective":"Distribuir prioridades semanales considerando capacidad real, carga de pipeline, urgencia y valor esperado sin premiar únicamente volumen bruto.","core":"Más oportunidades no siempre significan más productividad. Cuando un agente acumula demasiados próximos pasos vencidos, propuestas sin seguimiento o tareas simultáneas, la cartera pierde velocidad. La supervisión debe proteger capacidad para actividades que mueven oportunidades y redistribuir cuando la carga supera lo razonable. La capacidad se evalúa con evidencia operativa, no con percepciones personales.","method":"Marco CARGA: Contar compromisos activos; Agrupar por etapa y urgencia; Revisar próximos pasos vencidos; Graduar capacidad disponible; Asignar tres prioridades semanales. Cada prioridad debe indicar resultado esperado, actividad crítica y señal de cierre de la semana.","case":"Una agente tiene 42 oportunidades abiertas y 18 seguimientos vencidos; otro agente tiene 14 oportunidades y capacidad disponible. El supervisor no reparte nuevos leads por turno automático: primero limpia oportunidades sin próximo paso, reprograma seguimientos válidos y redistribuye solo lo autorizado y necesario.","practice":"Construye una tabla de capacidad para cuatro agentes ficticios sin usar datos personales reales. Incluye oportunidades activas, próximos pasos vencidos, propuestas abiertas, horas disponibles y tres prioridades. Explica una redistribución y su criterio.","platform":"Revisar tareas vencidas, próximos pasos y carga por etapa en Compás One. Toda reasignación debe conservar origen, historial y responsable; no eliminar actividad para hacer ver más limpio el tablero.","video":"Mostrar el error de repartir leads sin mirar carga. Presentar CARGA con cuatro columnas simples. Resolver un caso de saturación frente a capacidad ociosa. Mostrar cómo cerrar una semana con tres prioridades verificables. Cierre: capacidad protegida produce mejor seguimiento que acumulación sin control."},
    {"p":3,"t":"Forecast responsable y decisiones de intervención","d":"Construye una previsión basada en probabilidad, evidencia y próximos pasos para decidir dónde acompañar, acelerar, corregir o dejar avanzar al equipo.","m":37,"objective":"Crear un forecast útil para decisiones semanales distinguiendo compromiso, mejor escenario y riesgo, sin convertir la previsión en una promesa de ventas.","core":"Un forecast no es una cuota disfrazada ni una suma optimista del pipeline. Debe reflejar la evidencia disponible: etapa, calidad del diagnóstico, decisión identificada, próximo paso, fecha, valor y riesgo. El supervisor usa la previsión para decidir dónde intervenir, no para presionar a convertir oportunidades inciertas en números comprometidos.","method":"Marco PRISMA: Probabilidad sustentada; Riesgo explícito; Impacto económico; Siguiente paso fechado; Momento de decisión; Acción del supervisor. Clasifica cada oportunidad relevante como compromiso, probable o exploratoria y construye tres vistas: base, probable y mejor escenario. Las diferencias deben explicarse por evidencia, no por deseo.","case":"El equipo reporta $120,000 en pipeline, pero solo $35,000 tienen decisión identificada y próximo paso fechado. El supervisor presenta forecast base de $35,000, probable de $62,000 y escenario alto de $90,000, documentando qué tendría que ocurrir para mover cada oportunidad. No promete $120,000.","practice":"Selecciona diez oportunidades simuladas y clasifícalas con PRISMA. Calcula escenario base, probable y alto. Define tres intervenciones del supervisor: una de coaching, una de desbloqueo operativo y una donde no debe intervenir.","platform":"Usar montos, etapas y próximos pasos registrados en Compás One como fuente operativa. Señalar datos incompletos en vez de inventarlos. Mantener separado forecast de meta y nunca alterar probabilidad solo para alcanzar una cifra deseada.","video":"Abrir con la diferencia entre pipeline y forecast. Presentar PRISMA y tres escenarios. Resolver el caso de $120,000 de pipeline con solo $35,000 comprometidos. Mostrar qué decisiones habilita el forecast: coaching, desbloqueo, priorización o no intervención. Cerrar: un forecast útil explica la incertidumbre, no la esconde."}
  ]$j$::jsonb;
begin
  select id into v_course from public.courses where slug='nivel-4-liderazgo-supervision-comercial' limit 1;
  if v_course is null then raise exception 'Nivel 4 course is required'; end if;
  if exists(select 1 from public.courses where id=v_course and status<>'draft') then raise exception 'Nivel 4 must remain draft'; end if;

  select id into v_module from public.modules where course_id=v_course and position=3 limit 1;
  if v_module is null then
    insert into public.modules(course_id,title,description,position)
    values(v_course,'3. Dirección por KPIs y decisiones de equipo','Lee el embudo, protege capacidad y construye forecasts responsables para intervenir con evidencia.',3)
    returning id into v_module;
  else
    update public.modules set title='3. Dirección por KPIs y decisiones de equipo',description='Lee el embudo, protege capacidad y construye forecasts responsables para intervenir con evidencia.' where id=v_module;
  end if;

  for jl in select * from jsonb_array_elements(lessons) loop
    if exists(select 1 from public.lessons where module_id=v_module and position=(jl->>'p')::int) then
      update public.lessons set title=jl->>'t',description=jl->>'d',duration_minutes=(jl->>'m')::int,content=jsonb_build_object('objective',jl->>'objective','core',jl->>'core','method',jl->>'method','case',jl->>'case','practice',jl->>'practice','platform',jl->>'platform','video',jl->>'video') where module_id=v_module and position=(jl->>'p')::int;
    else
      insert into public.lessons(module_id,title,description,position,duration_minutes,content)
      values(v_module,jl->>'t',jl->>'d',(jl->>'p')::int,(jl->>'m')::int,jsonb_build_object('objective',jl->>'objective','core',jl->>'core','method',jl->>'method','case',jl->>'case','practice',jl->>'practice','platform',jl->>'platform','video',jl->>'video'));
    end if;
  end loop;
end $m$;
