-- Nivel 4 · Módulo 4 · Gestión de desempeño y conversaciones difíciles
-- Mantener curso en draft. No crea alumnos, resultados ni certificados.
do $m$
declare
  v_course uuid; v_module uuid; jl jsonb;
  lessons jsonb := '[
 {"p":1,"t":"Detectar incumplimiento sin etiquetar a la persona","d":"Distingue un evento aislado de un patrón de desempeño y prepara una conversación basada en evidencia.","m":36,"objective":"Identificar desviaciones relevantes con evidencia suficiente antes de intervenir.","core":"El supervisor separa hechos, impacto y contexto. No diagnostica actitud por intuición. Compara estándar acordado contra conducta observable, frecuencia, impacto comercial y apoyos ya ofrecidos. Un dato aislado abre una pregunta; un patrón verificable abre una intervención.","method":"Método HECHO: Hito o estándar esperado; Evidencia observable; Contexto relevante; Huella o impacto; Oportunidad de corrección.","case":"Una agente acumula seguimientos vencidos. En vez de asumir desinterés, el supervisor revisa distribución de cartera, registros, compromisos y bloqueos. Descubre una combinación de mala priorización y carga temporal, y define la conducta concreta a recuperar.","practice":"Analiza tres situaciones y redacta para cada una estándar, evidencia, impacto, pregunta de contexto y conducta esperada, evitando etiquetas personales.","platform":"Usa KPIs, tareas, pipeline y notas operativas de Compás One para reunir evidencia mínima. Registra solo información laboral necesaria y acuerdos verificables.","video":"Abre contrastando 'no está comprometido' con '7 seguimientos vencidos sobre 12 comprometidos'. Explica HECHO paso a paso, resuelve el caso y cierra mostrando cómo una conversación justa empieza por evidencia."},
 {"p":2,"t":"Conversación correctiva y acuerdo verificable","d":"Conduce conversaciones difíciles con claridad, respeto, responsabilidad y un siguiente paso medible.","m":38,"objective":"Corregir una desviación sin humillar, amenazar ni diluir el estándar.","core":"Una conversación correctiva protege simultáneamente a la persona, al cliente y al estándar. El supervisor describe la brecha, escucha contexto, confirma responsabilidad, acuerda una conducta específica y establece fecha de revisión. Consecuencias organizacionales solo se comunican cuando existen y corresponden a política; nunca se inventan como presión.","method":"Marco CLARO: Contexto; Lectura de evidencia; Aclaración y escucha; Responsabilidad acordada; Objetivo siguiente y revisión.","case":"Un agente promete fechas al cliente que operación no confirmó. El supervisor presenta dos casos documentados, escucha por qué ocurrió, reafirma el estándar de no prometer sin validación y acuerda usar confirmación interna antes de comunicar fechas durante las próximas dos semanas.","practice":"Prepara y simula una conversación CLARO. El observador califica precisión de evidencia, calidad de escucha, claridad del estándar y verificabilidad del acuerdo.","platform":"Documenta en Compás One el acuerdo operativo, responsable, fecha y evidencia de cumplimiento. Evita juicios, datos sensibles o transcripciones innecesarias.","video":"Representa primero una conversación agresiva y otra evasiva; muestra por qué ambas fallan. Después ejecuta CLARO con el mismo caso y termina con el acuerdo escrito en lenguaje observable."},
 {"p":3,"t":"Recuperación, escalamiento proporcional y reconocimiento","d":"Da seguimiento a la mejora, decide cuándo apoyar o escalar y reconoce desempeño sostenible.","m":38,"objective":"Gestionar el ciclo posterior a la conversación correctiva con criterios consistentes y proporcionales.","core":"El seguimiento pregunta si la conducta cambió y si el resultado asociado mejora. Si hay avance, se reconoce específicamente y se retira apoyo de forma gradual. Si no hay avance, se distingue falta de habilidad, recursos, claridad o cumplimiento. El escalamiento debe seguir políticas vigentes, autoridad del rol y evidencia; nunca automatizar sanciones. El reconocimiento refuerza conductas replicables, no favoritismos ni resultados aislados.","method":"Ruta RECUPERA: Revisar evidencia; Evaluar avance; Corregir soporte; Ubicar causa persistente; Proporcionalidad; Escalar según política; Reconocer mejora; Acordar continuidad.","case":"Tras dos semanas, la agente del primer caso reduce seguimientos vencidos de forma consistente. El supervisor reconoce la mejora, mantiene una revisión semanal temporal y retira el apoyo extra cuando el hábito se sostiene. En un segundo caso sin cambio, documenta evidencia y deriva el siguiente paso a la autoridad correspondiente.","practice":"Construye un árbol de decisión con cuatro escenarios: mejora total, mejora parcial, bloqueo de capacidad y repetición sin cambio. Define evidencia, apoyo, revisión y punto de escalamiento para cada uno.","platform":"Configura revisiones y tareas de seguimiento en Compás One. Usa estados y notas objetivas para conservar trazabilidad; cualquier proceso disciplinario formal queda fuera de automatizaciones comerciales y sujeto a política aplicable.","video":"Explica por qué corregir no termina al cerrar la reunión. Recorre RECUPERA, compara mejora parcial con reincidencia y termina mostrando reconocimiento específico de una conducta sostenible."}
]'::jsonb;
begin
 select id into v_course from public.courses where slug='nivel-4-liderazgo-supervision-comercial' limit 1;
 if v_course is null then raise exception 'Nivel 4 course is required'; end if;
 if exists(select 1 from public.courses where id=v_course and status<>'draft') then raise exception 'Nivel 4 must remain draft'; end if;
 select id into v_module from public.modules where course_id=v_course and position=4 limit 1;
 if v_module is null then insert into public.modules(course_id,title,description,position) values(v_course,'4. Gestión de desempeño y conversaciones difíciles','Detecta desviaciones con evidencia, conversa con claridad y gestiona recuperación o escalamiento proporcional.',4) returning id into v_module; else update public.modules set title='4. Gestión de desempeño y conversaciones difíciles',description='Detecta desviaciones con evidencia, conversa con claridad y gestiona recuperación o escalamiento proporcional.' where id=v_module; end if;
 for jl in select * from jsonb_array_elements(lessons) loop
  if exists(select 1 from public.lessons where module_id=v_module and position=(jl->>'p')::int) then
   update public.lessons set title=jl->>'t',description=jl->>'d',lesson_type='text',duration_minutes=(jl->>'m')::int,content_html='<h2>Objetivo</h2><p>'||(jl->>'objective')||'</p><h2>Contenido</h2><p>'||(jl->>'core')||'</p><h2>Método</h2><p>'||(jl->>'method')||'</p><h2>Caso</h2><p>'||(jl->>'case')||'</p><h2>Ejercicio</h2><p>'||(jl->>'practice')||'</p><h2>Aplicación en Compás One</h2><p>'||(jl->>'platform')||'</p><h2>Guion de video</h2><p>'||(jl->>'video')||'</p>',updated_at=now() where module_id=v_module and position=(jl->>'p')::int;
  else
   insert into public.lessons(module_id,title,description,lesson_type,content_html,duration_minutes,position,is_preview) values(v_module,jl->>'t',jl->>'d','text','<h2>Objetivo</h2><p>'||(jl->>'objective')||'</p><h2>Contenido</h2><p>'||(jl->>'core')||'</p><h2>Método</h2><p>'||(jl->>'method')||'</p><h2>Caso</h2><p>'||(jl->>'case')||'</p><h2>Ejercicio</h2><p>'||(jl->>'practice')||'</p><h2>Aplicación en Compás One</h2><p>'||(jl->>'platform')||'</p><h2>Guion de video</h2><p>'||(jl->>'video')||'</p>',(jl->>'m')::int,(jl->>'p')::int,false);
  end if;
 end loop;
end $m$;