-- Compás Academy · Nivel 4 · Módulo 5 · Operación del equipo, calidad y escalamiento de servicio
-- Curso permanece draft. No emite certificación ni crea datos ficticios.

do $m$
declare
  v_course uuid;
  v_module uuid;
  jl jsonb;
  curriculum jsonb := $c$
  [
    {"p":1,"t":"Control operativo con acuerdos de servicio internos","d":"Convierte la operación diaria en compromisos observables sin confundir velocidad con calidad.","m":36,"objective":"Diseñar acuerdos internos de atención con responsable, condición de inicio, tiempo objetivo, evidencia y regla de escalamiento.","core":"Un supervisor no controla la operación preguntando constantemente si todo está bien. La controla haciendo visible qué debe ocurrir, quién responde y cuándo una excepción requiere intervención. Un acuerdo interno de servicio no es una promesa comercial al cliente: es una referencia operativa que debe adaptarse a capacidad, prioridad y política vigente. La velocidad nunca justifica omitir diagnóstico, consentimiento, documentación o controles necesarios.","method":"Marco PULSO: Prioridad del caso; Umbral o tiempo objetivo; Líder responsable; Señal de cumplimiento; Observación de excepción. PULSO permite distinguir flujo normal de excepción sin inventar compromisos externos.","case":"Un lead calificado queda sin siguiente paso porque ventas cree que soporte debe completar un dato y soporte cree que ventas sigue siendo responsable. El supervisor usa PULSO: define prioridad, responsable actual, tiempo interno, evidencia esperada y condición que dispara escalamiento.","practice":"Diseña cuatro acuerdos PULSO para lead nuevo, propuesta pendiente, cliente recién activado e incidente operativo. Señala cuáles son objetivos internos y cuáles requerirían autorización antes de comunicarse como compromiso al cliente.","platform":"En Compás One revisar tareas vencidas, conversaciones sin responsable y oportunidades sin siguiente paso. Registrar responsable, fecha objetivo y evidencia usando únicamente casos reales cuando existan.","video":"Abrir con un caso que se pierde entre dos áreas. Explicar por qué un SLA interno no equivale a una garantía al cliente. Construir PULSO en pantalla. Mostrar flujo normal frente a excepción. Cerrar con la pregunta: ¿quién es responsable ahora y qué evidencia demostrará que avanzó?"},
    {"p":2,"t":"Handoffs que conservan contexto y calidad","d":"Transfiere clientes y oportunidades entre personas o áreas sin reiniciar la conversación ni perder responsabilidad.","m":38,"objective":"Ejecutar handoffs con contexto mínimo suficiente, aceptación explícita y continuidad verificable.","core":"Transferir no significa reenviar un mensaje. Un handoff de calidad conserva el propósito del cliente, lo ya confirmado, lo pendiente, los compromisos autorizados y el siguiente paso. Debe minimizar datos innecesarios y evitar que el cliente repita información que ya está disponible. La responsabilidad cambia solo cuando el receptor acepta el caso según el proceso definido.","method":"Marco PUENTE: Propósito del cliente; Último estado confirmado; Evidencia relevante; Necesidad pendiente; Titular que recibe; Enlace o siguiente acción. Antes de transferir se verifica que la información compartida sea necesaria para el trabajo.","case":"Un agente cierra una venta y escribe a implementación: ‘ya pagó, ayúdenlo’. Implementación desconoce alcance, contacto y siguiente paso. Con PUENTE recibe propósito, alcance confirmado, evidencia necesaria, pendiente, responsable y acción acordada; el cliente no comienza desde cero.","practice":"Reescribe tres handoffs deficientes usando PUENTE: ventas a onboarding, soporte a especialista y agente a supervisor. Elimina datos que no sean necesarios para ejecutar el siguiente paso.","platform":"Usar notas, tareas y relaciones de contacto de Compás One para conservar contexto operativo. Evitar copiar información sensible en campos libres cuando no sea necesaria.","video":"Mostrar un handoff de una línea y sus consecuencias. Presentar PUENTE. Construir una transferencia completa pero breve. Explicar aceptación de responsabilidad. Cerrar con la regla: transferimos contexto, no ruido; responsabilidad, no abandono."},
    {"p":3,"t":"Incidentes, escalamiento y recuperación del servicio","d":"Responde a fallas con contención, comunicación proporcional, corrección y aprendizaje operativo.","m":40,"objective":"Clasificar incidentes, contener impacto, escalar al nivel correcto y cerrar con acciones preventivas verificables.","core":"Cuando existe una falla, ocultarla o prometer una solución no autorizada aumenta el riesgo. El supervisor debe separar hechos de hipótesis, proteger al cliente y la operación, escalar cuando el impacto excede su autoridad y documentar lo necesario para aprender. Compensaciones, reembolsos, asuntos legales, seguridad, privacidad o compromisos extraordinarios siguen las políticas y autoridades correspondientes.","method":"Marco RESTAURA: Registrar hecho; Estimar impacto; Señalar responsable; Tomar contención segura; Autoridad y escalamiento; Actualizar a quien corresponda; Resolver y verificar; Aprender y prevenir.","case":"Un cliente reporta que una configuración no coincide con lo acordado. El supervisor no culpa al agente ni promete reembolso. Registra el hecho, contiene cambios adicionales, confirma alcance, escala si la solución excede autoridad, comunica el siguiente punto de actualización y después documenta causa y prevención.","practice":"Resuelve un escenario de incidente con RESTAURA. Distingue qué puedes decidir, qué debes escalar y qué nunca debes prometer sin autorización. Termina con una acción preventiva medible.","platform":"Registrar incidente como tarea/caso operativo con hechos, impacto, responsable, siguiente actualización y cierre. No registrar categorías sensibles innecesarias ni conclusiones no verificadas.","video":"Abrir con la diferencia entre problema e incidente. Recorrer RESTAURA desde el hecho hasta el aprendizaje. Mostrar cuándo detenerse y escalar. Incluir un ejemplo de comunicación sin promesas no autorizadas. Cerrar: recuperar confianza empieza por claridad, responsabilidad y seguimiento verificable."}
  ]$c$::jsonb;
begin
  select id into v_course from public.courses where slug='nivel-4-liderazgo-supervision-comercial' limit 1;
  if v_course is null then raise exception 'Nivel 4 course is required'; end if;

  select id into v_module from public.modules where course_id=v_course and position=5 limit 1;
  if v_module is null then
    insert into public.modules(course_id,title,description,position)
    values(v_course,'5. Operación del equipo, calidad y escalamiento de servicio','Control operativo, handoffs, incidentes y recuperación con responsabilidad verificable.',5)
    returning id into v_module;
  else
    update public.modules set title='5. Operación del equipo, calidad y escalamiento de servicio',description='Control operativo, handoffs, incidentes y recuperación con responsabilidad verificable.' where id=v_module;
  end if;

  for jl in select * from jsonb_array_elements(curriculum) loop
    if exists(select 1 from public.lessons where module_id=v_module and position=(jl->>'p')::int) then
      update public.lessons set title=jl->>'t',description=jl->>'d',duration_minutes=(jl->>'m')::int,
        content_html=jsonb_build_object('objective',jl->>'objective','core',jl->>'core','method',jl->>'method','case',jl->>'case','practice',jl->>'practice','platform',jl->>'platform','video',jl->>'video')::text
      where module_id=v_module and position=(jl->>'p')::int;
    else
      insert into public.lessons(module_id,title,description,position,duration_minutes,content_html)
      values(v_module,jl->>'t',jl->>'d',(jl->>'p')::int,(jl->>'m')::int,jsonb_build_object('objective',jl->>'objective','core',jl->>'core','method',jl->>'method','case',jl->>'case','practice',jl->>'practice','platform',jl->>'platform','video',jl->>'video')::text);
    end if;
  end loop;
end $m$;