-- Compás Academy · Nivel 5 · Dirección Comercial Avanzada
-- Módulo 1: De supervisor a director comercial. Curso en draft.

do $m$
declare
  v_course uuid; v_workspace uuid; v_module uuid; v_level4 uuid; jl jsonb;
  lessons jsonb := $c$[
    {"p":1,"t":"Pensar en sistema, no solo en resultados individuales","d":"Aprende a leer el área comercial como un sistema compuesto por mercado, capacidad, pipeline, conversión, recurrencia, talento y operación, evitando optimizar una métrica a costa del conjunto.","m":38,"html":"<h2>Objetivo</h2><p>Pasar de supervisar ejecución a dirigir un sistema comercial completo.</p><h3>Marco SISTEMA</h3><p><strong>S</strong>eñal: dato relevante. <strong>I</strong>nterdependencia: variables conectadas. <strong>S</strong>egmentación: evita promedios engañosos. <strong>T</strong>ensión: reconoce intercambios entre velocidad, calidad, costo y capacidad. <strong>E</strong>xperimento: prueba una intervención controlada. <strong>M</strong>edición: define qué debería cambiar. <strong>A</strong>prendizaje: escala, ajusta o detén según evidencia.</p><h3>Contenido</h3><p>Un director no pregunta únicamente cuánto vendió el equipo. Pregunta qué parte del sistema produjo ese resultado, si es repetible, qué capacidad consumió y qué riesgo genera. La dirección conecta adquisición, avance, cierre, activación, permanencia y expansión. Una mejora aislada deja de ser mejora cuando deteriora calidad, margen, capacidad o confianza.</p><h3>Caso</h3><p>Un equipo aumenta cierres 22%, pero duplica incidencias y cancelaciones tempranas. SISTEMA obliga a separar el efecto por canal, agente, plan y tiempo antes de escalar la práctica.</p><h3>Ejercicio</h3><p>Elige un KPI, dibuja cinco variables conectadas, formula una hipótesis causal y diseña un experimento de una semana sin comprometer clientes reales.</p><h3>Registro en Compás One</h3><p>Documenta señal, segmento, hipótesis, intervención, responsable, revisión y criterio de éxito.</p><h3>Guion de video</h3><p>Apertura: dirigir no es mirar un número más grande. Desarrollo: muestra un cierre que provoca sobrecarga. Explica SISTEMA. Cierre: protege el resultado de hoy sin hipotecar el de mañana.</p>"},
    {"p":2,"t":"Convertir estrategia en prioridades comerciales ejecutables","d":"Traduce objetivos de negocio en pocas prioridades, indicadores de resultado y señales adelantadas que el equipo pueda ejecutar y revisar.","m":40,"html":"<h2>Objetivo</h2><p>Transformar intención estratégica en decisiones operativas medibles.</p><h3>Marco NORTE</h3><p><strong>N</strong>egocio: resultado relevante. <strong>O</strong>bstáculo: restricción principal. <strong>R</strong>esultado: KPI final. <strong>T</strong>racción: señales adelantadas influenciables. <strong>E</strong>jecución: responsables, límites y revisión.</p><h3>Contenido</h3><p>Una estrategia pierde utilidad cuando se convierte en una lista extensa de iniciativas. NORTE conecta cada prioridad con una restricción real y señales que el equipo puede mover durante el periodo. Las metas internas no deben convertirse en garantías al cliente.</p><h3>Caso</h3><p>La empresa quiere crecer 30%. El director detecta que la restricción está en oportunidades calificadas y seguimiento tardío, por lo que prioriza diagnósticos completos y oportunidades con próximo paso vigente.</p><h3>Ejercicio</h3><p>Convierte un objetivo amplio en una tarjeta NORTE con baseline, resultado, obstáculo, dos señales adelantadas, responsable y revisión.</p><h3>Registro en Compás One</h3><p>Registra prioridad, propietario, métrica, baseline, objetivo interno, señales y fecha de revisión.</p><h3>Guion de video</h3><p>Apertura: una meta no es una estrategia. Desarrollo: transforma una meta con NORTE. Cierre: el equipo debe saber qué mover esta semana y por qué importa.</p>"},
    {"p":3,"t":"Gobernanza de decisiones y ritmo de dirección","d":"Diseña una cadencia ejecutiva que diferencie monitoreo, decisiones, escalamiento y aprendizaje para evitar reuniones que solo reportan información.","m":42,"html":"<h2>Objetivo</h2><p>Crear un sistema de dirección donde cada reunión tenga propósito, evidencia y decisión.</p><h3>Marco GOBIERNA</h3><p><strong>G</strong>ap: desviación significativa. <strong>O</strong>rigen: evidencia. <strong>B</strong>loqueo: restricción. <strong>I</strong>mpacto: prioridad. <strong>E</strong>lección: decisión. <strong>R</strong>esponsable: propietario. <strong>N</strong>ext step: siguiente paso. <strong>A</strong>prendizaje: revisión del efecto.</p><h3>Contenido</h3><p>La gobernanza separa salud del sistema, decisiones, riesgos y aprendizaje. Una reunión ejecutiva no debe limitarse a leer dashboards; debe convertir evidencia en decisiones trazables.</p><h3>Caso</h3><p>Cada supervisor presenta veinte números y nadie decide. GOBIERNA reduce la discusión a tres gaps, evidencia, decisiones y responsables.</p><h3>Ejercicio</h3><p>Diseña una agenda de 45 minutos: 10 señales, 20 decisiones, 10 riesgos y 5 compromisos, con dueño y fecha para cada decisión.</p><h3>Registro en Compás One</h3><p>Registra decisiones, responsables, evidencia mínima, riesgos y próximos pasos sin duplicar dashboards.</p><h3>Guion de video</h3><p>Apertura: una reunión sin decisión es lectura colectiva de pantalla. Desarrollo: explica las cuatro conversaciones y GOBIERNA. Cierre: toda reunión termina con decisiones trazables y fechas.</p>"}
  ]$c$::jsonb;
begin
  select id,workspace_id into v_level4,v_workspace from public.courses where slug='nivel-4-liderazgo-supervision-comercial' limit 1;
  if v_level4 is null then raise exception 'Nivel 4 course is required before Nivel 5'; end if;
  select id into v_course from public.courses where slug='nivel-5-direccion-comercial-avanzada-compas' limit 1;
  if v_course is null then
    insert into public.courses(title,slug,subtitle,description,category,status,featured,instructor_name,duration_label,workspace_id)
    values('Nivel 5 · Dirección Comercial Avanzada','nivel-5-direccion-comercial-avanzada-compas','De supervisar equipos a dirigir el sistema comercial','Formación avanzada para convertir estrategia, capacidad, talento, pipeline y permanencia en un sistema comercial gobernable y escalable.','Dirección Comercial','draft',false,'Equipo Compás Evolution','12–14 h',v_workspace)
    returning id into v_course;
  end if;
  select id into v_module from public.modules where course_id=v_course and position=1 limit 1;
  if v_module is null then
    insert into public.modules(course_id,title,description,position)
    values(v_course,'1. De supervisor a director comercial','Pensamiento sistémico, prioridades estratégicas y gobernanza de decisiones.',1)
    returning id into v_module;
  end if;
  for jl in select value from jsonb_array_elements(lessons) loop
    if exists(select 1 from public.lessons where module_id=v_module and position=(jl->>'p')::int) then
      update public.lessons set title=jl->>'t',description=jl->>'d',lesson_type='text',content_html=jl->>'html',duration_minutes=(jl->>'m')::int,is_preview=false,updated_at=now() where module_id=v_module and position=(jl->>'p')::int;
    else
      insert into public.lessons(module_id,title,description,lesson_type,content_html,duration_minutes,position,is_preview)
      values(v_module,jl->>'t',jl->>'d','text',jl->>'html',(jl->>'m')::int,(jl->>'p')::int,false);
    end if;
  end loop;
end $m$;
