-- Compás Academy · Nivel 5 · Módulo 1 · Evaluación formativa
-- 12 reactivos, aprobación 80% (mínimo 10/12).

create table if not exists public.freelance_level5_module1_assessment (
  id bigint generated by default as identity primary key,
  position integer not null unique,
  prompt text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option char(1) not null check (correct_option in ('A','B','C','D')),
  explanation text not null,
  created_at timestamptz not null default now()
);

alter table public.freelance_level5_module1_assessment enable row level security;
revoke all on public.freelance_level5_module1_assessment from public,anon,authenticated;
grant all on public.freelance_level5_module1_assessment to service_role;

insert into public.freelance_level5_module1_assessment(position,prompt,option_a,option_b,option_c,option_d,correct_option,explanation) values
(1,'¿Qué distingue principalmente a una lectura de dirección comercial de una lectura de supervisión individual?','Observa únicamente cierres','Conecta resultados con capacidad, calidad, permanencia y otras variables del sistema','Elimina todos los KPIs individuales','Sustituye datos por intuición','B','La dirección interpreta interdependencias y sostenibilidad, no solo resultados aislados.'),
(2,'En el marco SISTEMA, después de identificar una señal relevante, ¿qué debe analizarse?','La interdependencia con otras variables','El color del dashboard','Solo el promedio general','Una meta de ventas mayor','A','Una señal aislada puede inducir decisiones equivocadas si no se entiende qué otras variables afecta.'),
(3,'Si los cierres crecen pero también aumentan cancelaciones tempranas, la mejor primera lectura es:','Celebrar el crecimiento y no revisar nada','Bajar precios automáticamente','Investigar si el crecimiento está deteriorando calidad, activación o ajuste del cliente','Culpar al equipo de servicio','C','El pensamiento sistémico busca efectos secundarios y origen antes de intervenir.'),
(4,'¿Para qué sirve el componente Experimento de SISTEMA?','Para cambiar toda la operación a la vez','Para probar una hipótesis mediante una intervención controlada','Para garantizar el resultado','Para evitar medir','B','El experimento reduce el riesgo de escalar una explicación no verificada.'),
(5,'¿Cuál es la función principal de NORTE?','Convertir un objetivo amplio en una prioridad ejecutable y medible','Crear slogans para el equipo','Reemplazar el pipeline','Asignar comisiones','A','NORTE conecta resultado de negocio, restricción, métricas, señales adelantadas y ejecución.'),
(6,'Una empresa quiere crecer 30%. ¿Cuál de estas acciones representa mejor una aplicación de NORTE?','Exigir 30% más cierres a todos','Identificar la restricción principal y definir señales adelantadas que el equipo pueda mover','Prometer 30% más ventas a clientes','Duplicar todas las actividades sin medir capacidad','B','La estrategia debe centrarse en la restricción y en acciones influenciables, no en trasladar la meta como presión.'),
(7,'¿Qué diferencia a una señal adelantada de un KPI final?','La señal adelantada puede influirse antes de conocer el resultado final','Siempre tiene valor monetario','No necesita seguimiento','Solo se usa una vez al año','A','Las señales adelantadas ayudan a intervenir durante el periodo, no solo a explicar lo ocurrido al final.'),
(8,'¿Qué debe evitarse al traducir una meta interna a ejecución comercial?','Definir responsables','Confundirla con una promesa de resultado al cliente','Medir un baseline','Revisarla semanalmente','B','Los objetivos internos no deben convertirse en garantías comerciales.'),
(9,'En GOBIERNA, ¿qué debe ocurrir antes de atribuir una causa a una desviación?','Buscar evidencia de origen','Asignar culpa','Cambiar al responsable','Eliminar el KPI','A','La gobernanza separa hechos de explicaciones no verificadas.'),
(10,'¿Cuál es el mejor propósito de una reunión de dirección comercial?','Leer en voz alta todos los dashboards','Convertir evidencia y riesgos en decisiones trazables','Revisar únicamente ventas cerradas','Aumentar la duración de las reuniones','B','Los datos pueden revisarse antes; el valor de la reunión está en decidir, asignar y dar seguimiento.'),
(11,'¿Qué información mínima debe quedar registrada después de una decisión ejecutiva?','Decisión, responsable, evidencia relevante, riesgo y próximo paso con fecha','Toda la conversación palabra por palabra','Solo el nombre del director','Ninguna; basta recordarla','A','La trazabilidad requiere suficiente contexto para ejecutar y revisar sin duplicar información innecesaria.'),
(12,'Si una iniciativa mejora una métrica pero deteriora margen, capacidad y permanencia, un director debería:','Escalarla porque la métrica principal mejoró','Ignorar los efectos secundarios','Reevaluarla como sistema y ajustar o detener según evidencia','Convertirla en estándar inmediatamente','C','La dirección protege la sostenibilidad del sistema y no optimiza una métrica a costa del conjunto.')
on conflict(position) do update set
  prompt=excluded.prompt,option_a=excluded.option_a,option_b=excluded.option_b,option_c=excluded.option_c,option_d=excluded.option_d,correct_option=excluded.correct_option,explanation=excluded.explanation;

comment on table public.freelance_level5_module1_assessment is
'Banco interno Nivel 5 Módulo 1. 12 reactivos. Criterio pedagógico: 80%, mínimo 10 correctas. No expuesto directamente a alumnos.';
