-- Compás Academy · Nivel 5 · Dirección Comercial Avanzada
-- Módulo 2: Planeación comercial y arquitectura de crecimiento. Curso en draft.

do $m$
declare
  v_course uuid; v_module uuid; jl jsonb;
  lessons jsonb := $c$[
    {"p":1,"t":"Arquitectura de crecimiento: elegir dónde crecer","d":"Segmenta fuentes de crecimiento y evita confundir más actividad con una estrategia de expansión sostenible.","m":40,"html":"<h2>Objetivo</h2><p>Diseñar una tesis de crecimiento basada en segmentos, canales, oferta, permanencia y capacidad real.</p><h3>Marco MAPEA</h3><p><strong>M</strong>ercado: dónde existe oportunidad. <strong>A</strong>juste: qué problema y oferta encajan. <strong>P</strong>otencial: tamaño y calidad de la oportunidad. <strong>E</strong>conomía: costo, margen y permanencia esperada. <strong>A</strong>puesta: hipótesis priorizada y medible.</p><h3>Contenido</h3><p>Crecer no significa pedir más ventas a todos los canales. La dirección separa crecimiento por adquisición, conversión, expansión y permanencia; después identifica qué segmento y oferta justifican capacidad adicional. Una apuesta se trata como hipótesis, no como garantía.</p><h3>Caso</h3><p>Dos canales producen el mismo número de cierres, pero uno requiere el doble de seguimiento y presenta mayor cancelación temprana. MAPEA obliga a comparar calidad, costo y capacidad consumida antes de asignar presupuesto.</p><h3>Ejercicio</h3><p>Construye una matriz con tres segmentos y dos canales. Puntúa ajuste, potencial, economía, capacidad requerida y evidencia disponible. Elige una sola apuesta para probar.</p><h3>Registro en Compás One</h3><p>Documenta segmento, canal, oferta, hipótesis, baseline, capacidad requerida, señal de calidad, responsable y fecha de revisión.</p><h3>Guion de video</h3><p>Apertura: crecer en todas partes suele ser no elegir. Desarrollo: compara dos canales con el mismo cierre y distinta calidad. Explica MAPEA. Cierre: una apuesta de crecimiento debe decir dónde sí, dónde no y qué evidencia cambiaría la decisión.</p>"},
    {"p":2,"t":"Capacidad comercial y metas que el sistema puede sostener","d":"Convierte demanda y objetivos en capacidad necesaria, límites operativos y escenarios antes de comprometer recursos.","m":42,"html":"<h2>Objetivo</h2><p>Planear metas desde capacidad y restricciones, no desde deseos aislados.</p><h3>Marco CAPAZ</h3><p><strong>C</strong>arga: volumen esperado por etapa. <strong>A</strong>tención: tiempo y esfuerzo requeridos. <strong>P</strong>roductividad: throughput observado por rol. <strong>A</strong>mortiguador: reserva para variación, aprendizaje e incidencias. <strong>Z</strong>ona límite: umbral que dispara ajuste o escalamiento.</p><h3>Contenido</h3><p>Una meta comercial necesita una hipótesis de capacidad. La dirección estima cuánto trabajo entra, cuánto puede procesarse con calidad y dónde aparecerá la cola. No se debe planear al 100% de ocupación: la variabilidad, el entrenamiento y los incidentes requieren margen. Los supuestos deben quedar visibles.</p><h3>Caso</h3><p>Marketing propone duplicar leads. El equipo puede contactar el volumen, pero no completar diagnósticos ni seguimientos dentro del estándar interno. CAPAZ muestra que la restricción no es generación sino atención calificada.</p><h3>Ejercicio</h3><p>Calcula tres escenarios de volumen usando productividad histórica y un amortiguador explícito. Define el umbral que obligaría a reducir entrada, reasignar carga o ampliar capacidad.</p><h3>Registro en Compás One</h3><p>Registra volumen previsto, capacidad por etapa, supuesto de productividad, amortiguador, zona límite y decisión asociada.</p><h3>Guion de video</h3><p>Apertura: una meta sin capacidad es una deuda operativa. Desarrollo: muestra cómo más leads crean una cola invisible. Explica CAPAZ. Cierre: crecer con calidad exige saber cuánto puede absorber cada etapa y cuándo dejar de empujar.</p>"},
    {"p":3,"t":"Escenarios, recursos y portafolio de apuestas comerciales","d":"Construye escenarios base, favorable y adverso para asignar recursos sin tratar el forecast como certeza.","m":44,"html":"<h2>Objetivo</h2><p>Tomar decisiones de inversión y capacidad bajo incertidumbre con escenarios explícitos.</p><h3>Marco ESCALA</h3><p><strong>E</strong>scenario: base, favorable y adverso. <strong>S</strong>upuestos: variables que explican cada escenario. <strong>C</strong>apacidad: recursos necesarios y límites. <strong>A</strong>puesta: iniciativa y tamaño reversible. <strong>L</strong>ímites: señales para frenar, ampliar o corregir. <strong>A</strong>prendizaje: evidencia que actualiza el plan.</p><h3>Contenido</h3><p>La planeación avanzada no intenta adivinar un único futuro. Define escenarios y decisiones condicionadas. Los recursos se asignan por etapas: primero evidencia, después expansión. Un escenario adverso no es pesimismo; es preparación para proteger caja, calidad y clientes.</p><h3>Caso</h3><p>Una nueva alianza podría generar entre 40 y 140 oportunidades mensuales. En vez de contratar para 140 desde el primer día, el director define capacidad inicial, triggers de ampliación y límites de calidad.</p><h3>Ejercicio</h3><p>Diseña tres escenarios para una apuesta real. En cada uno especifica volumen, conversión como rango, capacidad, costo controlable, riesgo, trigger de decisión y acción reversible.</p><h3>Registro en Compás One</h3><p>Registra escenario, supuestos, rango esperado, recursos autorizados, límites, trigger, decisión y aprendizaje. No registres el escenario favorable como compromiso al cliente.</p><h3>Guion de video</h3><p>Apertura: un forecast no elimina incertidumbre. Desarrollo: presenta una alianza con tres volúmenes posibles. Explica ESCALA. Cierre: la dirección profesional no promete acertar el futuro; prepara decisiones mejores para varios futuros.</p>"}
  ]$c$::jsonb;
begin
  select id into v_course from public.courses where slug='nivel-5-direccion-comercial-avanzada-compas' limit 1;
  if v_course is null then raise exception 'Nivel 5 course is required before Module 2'; end if;
  select id into v_module from public.modules where course_id=v_course and position=2 limit 1;
  if v_module is null then
    insert into public.modules(course_id,title,description,position)
    values(v_course,'2. Planeación comercial y arquitectura de crecimiento','Segmentación de crecimiento, capacidad, escenarios y asignación disciplinada de recursos.',2)
    returning id into v_module;
  end if;
  for jl in select value from jsonb_array_elements(lessons) loop
    if exists(select 1 from public.lessons where module_id=v_module and position=(jl->>'p')::int) then
      update public.lessons set title=jl->>'t',description=jl->>'d',lesson_type='text',content_html=jl->>'html',duration_minutes=(jl->>'m')::int,is_preview=false,updated_at=now() where module_id=v_module and position=(jl->>'p')::int;
    else
      insert into public.lessons(module_id,title,description,lesson_type,content_html,duration_minutes,position,is_preview)
      values(v_module,jl->>'t',jl->>'d','text',jl->>'html',(jl->>'m')::int,(jl->>'p')::int,false);
    end if;
  end loop;
end $m$;