-- Compás Academy · Nivel 5 · Módulo 2 · Evaluación formativa
-- 12 reactivos, aprobación 80% (mínimo 10/12).

create table if not exists public.freelance_level5_module2_assessment (
  id bigint generated by default as identity primary key,
  position integer not null unique,
  prompt text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option char(1) not null check (correct_option in ('A','B','C','D')),
  explanation text not null,
  created_at timestamptz not null default now()
);
alter table public.freelance_level5_module2_assessment enable row level security;
revoke all on public.freelance_level5_module2_assessment from public,anon,authenticated;
grant all on public.freelance_level5_module2_assessment to service_role;

insert into public.freelance_level5_module2_assessment(position,prompt,option_a,option_b,option_c,option_d,correct_option,explanation) values
(1,'¿Cuál es el propósito principal de MAPEA?','Elegir una apuesta de crecimiento con evidencia de mercado, ajuste, potencial y economía','Aumentar actividad en todos los canales','Garantizar crecimiento','Eliminar la segmentación','A','MAPEA obliga a elegir dónde crecer y con qué hipótesis, en vez de dispersar recursos.'),
(2,'Dos canales cierran lo mismo, pero uno consume más seguimiento y cancela más. ¿Qué debe hacer primero la dirección?','Asignarles el mismo presupuesto','Comparar calidad, economía y capacidad consumida antes de escalar','Cerrar el canal más nuevo sin analizar','Subir la meta a ambos','B','El volumen de cierres aislado no describe la calidad económica u operativa del canal.'),
(3,'En MAPEA, una apuesta comercial debe tratarse como:','Una garantía','Una hipótesis priorizada y medible','Una orden permanente','Una promesa al cliente','B','La apuesta se valida con evidencia y puede cambiar si los supuestos no se sostienen.'),
(4,'¿Qué combinación representa mejor fuentes distintas de crecimiento?','Adquisición, conversión, expansión y permanencia','Solo llamadas y correos','Precio y descuento únicamente','Reuniones y reportes','A','La arquitectura distingue mecanismos de crecimiento para no reducir todo a captar más leads.'),
(5,'¿Para qué sirve CAPAZ?','Para planear metas considerando carga, atención, productividad, amortiguador y límites','Para ocupar al equipo al 100%','Para sustituir el forecast','Para eliminar estándares de calidad','A','CAPAZ convierte demanda en una hipótesis explícita de capacidad sostenible.'),
(6,'¿Por qué no conviene planear al 100% de ocupación?','Porque siempre sobran recursos','Porque variación, aprendizaje e incidencias requieren margen operativo','Porque los KPIs dejan de funcionar','Porque elimina la necesidad de leads','B','Un sistema sin amortiguador forma colas y deteriora calidad cuando aparece variabilidad.'),
(7,'Marketing duplica leads, pero el cuello está en diagnósticos y seguimiento. ¿Cuál es la mejor decisión inicial?','Duplicar todavía más los leads','Reconocer la restricción de atención y ajustar entrada o capacidad','Prometer respuesta inmediata','Ignorar la cola','B','Empujar más trabajo hacia una etapa restringida aumenta inventario y retrasos.'),
(8,'La zona límite de CAPAZ debe indicar:','Cuándo una señal obliga a ajustar entrada, carga o capacidad','El máximo número de reuniones posibles sin importar calidad','Una meta pública para clientes','Solo el presupuesto anual','A','El límite convierte una señal operativa en una regla de decisión anticipada.'),
(9,'¿Qué distingue a ESCALA de un forecast de un solo número?','Usa escenarios, supuestos y decisiones condicionadas','Elimina la incertidumbre','Siempre elige el escenario favorable','No requiere límites','A','ESCALA reconoce incertidumbre y prepara acciones para futuros diferentes.'),
(10,'Una alianza puede generar entre 40 y 140 oportunidades mensuales. ¿Qué práctica es más responsable?','Contratar desde el inicio para 140 sin evidencia','Definir capacidad inicial y triggers para ampliar según evidencia','Rechazar la alianza por no conocer un número exacto','Registrar 140 como compromiso comercial','B','La capacidad puede ampliarse por etapas cuando señales verificables justifican la inversión.'),
(11,'En un escenario adverso, el objetivo es principalmente:','Ser pesimista','Preparar decisiones que protejan caja, calidad y clientes','Cancelar todas las iniciativas','Ocultar el riesgo al equipo','B','El escenario adverso permite anticipar límites y acciones, no predecir fracaso.'),
(12,'¿Cuál es la mejor regla para asignar recursos a una apuesta incierta?','Asignar todo desde el primer día','Asignar por etapas, con límites y evidencia para ampliar, corregir o detener','Copiar el presupuesto del año anterior','Usar únicamente intuición','B','La inversión escalonada conserva reversibilidad y hace que el aprendizaje gobierne la expansión.')
on conflict (position) do update set prompt=excluded.prompt,option_a=excluded.option_a,option_b=excluded.option_b,option_c=excluded.option_c,option_d=excluded.option_d,correct_option=excluded.correct_option,explanation=excluded.explanation;