-- Compás Academy · Nivel 5 · Dirección Comercial Avanzada
-- Módulo 3: Gobierno de KPIs, forecast y economía comercial. Curso permanece draft.

do $m$
declare
  v_course uuid; v_module uuid; jl jsonb;
  lessons jsonb := $c$[
    {"p":1,"t":"Economía comercial: crecer con contribución, no solo con volumen","d":"Conecta adquisición, conversión, ingreso, costo de servir, permanencia y capacidad para distinguir crecimiento saludable de volumen que destruye valor.","m":42,"html":"<h2>Objetivo</h2><p>Leer la economía comercial antes de escalar inversión, actividad o equipo.</p><h3>Marco ECONOMIA</h3><p><strong>E</strong>ntrada: origen y costo de adquisición. <strong>C</strong>onversión: avance real por segmento. <strong>O</strong>peración: costo y capacidad para activar y servir. <strong>N</strong>eto: contribución después de costos atribuibles. <strong>O</strong>rigen de permanencia: retención, recurrencia o expansión observada. <strong>M</strong>omento de recuperación: cuándo se recupera la inversión comercial. <strong>I</strong>ncertidumbre: supuestos y rangos. <strong>A</strong>cción: escalar, corregir, experimentar o detener.</p><h3>Contenido</h3><p>Facturar más no garantiza crear más valor. La dirección debe comparar segmentos y canales usando definiciones consistentes, costos atribuibles y ventanas temporales equivalentes. CAC, recuperación y contribución son herramientas de decisión, no cifras decorativas. Cuando faltan costos completos o permanencia madura, se trabaja con rangos y se etiqueta la incertidumbre en lugar de fabricar precisión.</p><h3>Caso</h3><p>Canal A trae más clientes y parece ganador; Canal B trae menos, pero requiere menos soporte y conserva mejor a los clientes. ECONOMIA obliga a comparar contribución y recuperación por cohorte antes de aumentar presupuesto.</p><h3>Ejercicio</h3><p>Construye una ficha para dos canales con inversión, oportunidades, clientes, ingreso observado, costo atribuible, permanencia disponible y datos faltantes. Decide qué evidencia necesitas antes de escalar.</p><h3>Registro en Compás One</h3><p>Registra periodo, segmento, canal, inversión atribuible, volumen, conversión, ingreso, costo de servir disponible, contribución estimada, recuperación observada/estimada, supuestos y próxima revisión. No inventes valores faltantes.</p><h3>Guion de video</h3><p>Apertura: vender más puede empeorar el negocio. Desarrollo: compara dos canales que invierten el ranking al incorporar costo de servir y permanencia. Explica ECONOMIA. Cierre: escala valor repetible, no volumen aislado.</p>"},
    {"p":2,"t":"Forecast ejecutivo por escenarios y cartera de riesgos","d":"Construye un forecast trazable que separe pipeline observado, probabilidad sustentada, capacidad, riesgos y escenarios sin presentar estimaciones como garantías.","m":44,"html":"<h2>Objetivo</h2><p>Convertir pipeline y riesgos en escenarios útiles para decidir recursos y prioridades.</p><h3>Marco PREVE</h3><p><strong>P</strong>ipeline verificable: etapa y siguiente paso vigentes. <strong>R</strong>ango: escenario adverso, base y favorable. <strong>E</strong>videncia: razones observables para probabilidad y fecha. <strong>V</strong>ulnerabilidad: concentración, capacidad, dependencia o calidad. <strong>E</strong>lección: decisión que cambia según el escenario.</p><h3>Contenido</h3><p>El forecast ejecutivo no es una suma optimista de oportunidades. Debe distinguir cobertura, probabilidad, fecha, concentración y capacidad para cumplir. Las probabilidades requieren criterios consistentes; si no existe historial suficiente, se usan rangos explícitos. El objetivo del escenario no es adivinar el futuro, sino preparar decisiones diferentes ante futuros plausibles.</p><h3>Caso</h3><p>El pipeline nominal cubre 180% de la meta, pero 55% depende de tres oportunidades sin siguiente paso confirmado y el equipo de activación está cerca de capacidad. PREVE transforma una aparente holgura en riesgo visible y decisiones contingentes.</p><h3>Ejercicio</h3><p>Clasifica diez oportunidades por evidencia, fecha y riesgo; construye tres escenarios y define una decisión de contratación, inversión o prioridad que cambiaría entre ellos.</p><h3>Registro en Compás One</h3><p>Conserva etapa, siguiente paso, fecha, evidencia, rango/probabilidad según política, concentración, riesgo de capacidad y decisión asociada. Marca claramente estimaciones.</p><h3>Guion de video</h3><p>Apertura: forecast no significa promesa. Desarrollo: muestra cómo 180% de cobertura puede ocultar concentración y falta de evidencia. Explica PREVE. Cierre: un buen forecast prepara decisiones antes de que el resultado llegue.</p>"},
    {"p":3,"t":"Tablero ejecutivo y gobierno de KPIs","d":"Diseña un tablero de dirección que conecte crecimiento, eficiencia, calidad, permanencia, capacidad y riesgo con propietarios y reglas de intervención.","m":43,"html":"<h2>Objetivo</h2><p>Construir un sistema de KPIs que produzca decisiones y evite optimizaciones locales.</p><h3>Marco BALIZA</h3><p><strong>B</strong>alance: combina crecimiento, eficiencia, calidad, permanencia y capacidad. <strong>A</strong>tribución: define fuente y fórmula. <strong>L</strong>ímite: umbral o rango que merece atención. <strong>I</strong>nterpretación: segmento, cohorte y contexto. <strong>Z</strong>ona de decisión: observar, investigar, intervenir o escalar. <strong>A</strong>prendizaje: registra efecto y ajusta el sistema.</p><h3>Contenido</h3><p>Un tablero ejecutivo debe ser pequeño, estable y accionable. Cada KPI necesita definición, fuente, frecuencia, propietario y regla de lectura. Un indicador sin contexto puede incentivar conductas contraproducentes: velocidad sin calidad, cierres sin permanencia o crecimiento sin capacidad. Los umbrales internos son señales para investigar, no pruebas automáticas de culpa ni garantías externas.</p><h3>Caso</h3><p>El equipo mejora tiempo de respuesta pero cae la calidad del diagnóstico. BALIZA incorpora ambas señales y obliga a investigar la tensión antes de premiar una sola métrica.</p><h3>Ejercicio</h3><p>Diseña un tablero máximo de ocho KPIs. Para cada uno documenta fórmula, fuente, frecuencia, propietario, segmento, rango de atención y decisión posible. Elimina cualquier métrica que no cambie una decisión.</p><h3>Registro en Compás One</h3><p>Documenta diccionario de KPIs, fuente, periodo, propietario, umbral interno, excepción, decisión y fecha de revisión. Mantén trazabilidad de cambios de definición.</p><h3>Guion de video</h3><p>Apertura: más indicadores no significan más control. Desarrollo: muestra dos métricas que se contradicen y resuélvelas con BALIZA. Cierre: el tablero ejecutivo debe decir dónde mirar, qué investigar y cuándo decidir.</p>"}
  ]$c$::jsonb;
begin
  select id into v_course from public.courses where slug='nivel-5-direccion-comercial-avanzada-compas' limit 1;
  if v_course is null then raise exception 'Nivel 5 course is required before Module 3'; end if;
  select id into v_module from public.modules where course_id=v_course and position=3 limit 1;
  if v_module is null then
    insert into public.modules(course_id,title,description,position)
    values(v_course,'3. Gobierno de KPIs, forecast y economía comercial','Unit economics, forecast por escenarios, cartera de riesgos y tablero ejecutivo.',3)
    returning id into v_module;
  else
    update public.modules set title='3. Gobierno de KPIs, forecast y economía comercial',description='Unit economics, forecast por escenarios, cartera de riesgos y tablero ejecutivo.' where id=v_module;
  end if;
  for jl in select value from jsonb_array_elements(lessons) loop
    if exists(select 1 from public.lessons where module_id=v_module and position=(jl->>'p')::int) then
      update public.lessons set title=jl->>'t',description=jl->>'d',lesson_type='text',content_html=jl->>'html',duration_minutes=(jl->>'m')::int,is_preview=false,updated_at=now() where module_id=v_module and position=(jl->>'p')::int;
    else
      insert into public.lessons(module_id,title,description,lesson_type,content_html,duration_minutes,position,is_preview)
      values(v_module,jl->>'t',jl->>'d','text',jl->>'html',(jl->>'m')::int,(jl->>'p')::int,false);
    end if;
  end loop;
end $m$;
