-- Compás Academy · Nivel 5 · Módulo 3 · Evaluación formativa
-- 12 reactivos, aprobación 80% (mínimo 10/12).

create table if not exists public.freelance_level5_module3_assessment (
  id bigint generated by default as identity primary key,
  position integer not null unique,
  prompt text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option char(1) not null check (correct_option in ('A','B','C','D')),
  explanation text not null,
  created_at timestamptz not null default now()
);

alter table public.freelance_level5_module3_assessment enable row level security;
revoke all on public.freelance_level5_module3_assessment from public,anon,authenticated;
grant all on public.freelance_level5_module3_assessment to service_role;

insert into public.freelance_level5_module3_assessment(position,prompt,option_a,option_b,option_c,option_d,correct_option,explanation) values
(1,'¿Por qué el crecimiento de facturación no basta para evaluar la salud comercial?','Porque la facturación nunca importa','Porque debe relacionarse con costos atribuibles, capacidad, calidad y permanencia','Porque solo importan los leads','Porque el director debe evitar métricas financieras','B','El volumen puede crecer mientras deteriora contribución, capacidad o permanencia.'),
(2,'Si faltan datos maduros de permanencia para un canal nuevo, ¿qué debe hacer el director?','Inventar un promedio','Usar el mejor caso como dato real','Declarar la incertidumbre y trabajar con rangos o evidencia disponible','Eliminar el canal inmediatamente','C','La falta de madurez se gestiona explícitamente; no se fabrica precisión.'),
(3,'En ECONOMIA, el momento de recuperación sirve para:','Saber cuándo la inversión comercial se recupera bajo las definiciones usadas','Garantizar rentabilidad futura','Sustituir la contribución','Fijar salarios','A','El periodo de recuperación conecta inversión con retorno observado o estimado y debe documentar supuestos.'),
(4,'Dos canales tienen el mismo CAC. ¿Qué dato puede cambiar de forma importante la decisión de escala?','El nombre del canal','Costo de servir y permanencia por cohorte','El color del anuncio','El número de reuniones internas','B','CAC aislado no captura el valor posterior ni la carga operativa.'),
(5,'¿Cuál es la finalidad principal de PREVE?','Prometer una cifra exacta','Preparar decisiones ante escenarios plausibles usando evidencia y riesgos','Sumar todo el pipeline como ingreso seguro','Eliminar escenarios adversos','B','El forecast es una herramienta de decisión bajo incertidumbre, no una garantía.'),
(6,'Un pipeline cubre 180% de la meta, pero más de la mitad depende de tres oportunidades sin siguiente paso confirmado. ¿Qué lectura es más sólida?','Existe holgura garantizada','Hay riesgo de concentración y evidencia insuficiente que debe reflejarse en escenarios','La meta ya está cumplida','Debe duplicarse el precio','B','La cobertura nominal puede ocultar concentración y baja verificabilidad.'),
(7,'¿Qué evidencia fortalece una fecha estimada de cierre?','Deseo del vendedor','Siguiente paso acordado y señales verificables del proceso','La meta mensual','Una frase motivacional','B','Las fechas deben sustentarse en hechos del proceso, no en presión interna.'),
(8,'¿Qué diferencia un escenario de una promesa?','El escenario explicita supuestos, rango y decisiones contingentes','El escenario siempre es exacto','La promesa usa más datos','No existe diferencia','A','Los escenarios representan futuros plausibles y hacen visible la incertidumbre.'),
(9,'¿Qué característica debe tener un tablero ejecutivo eficaz?','La mayor cantidad posible de métricas','Pocos KPIs definidos, trazables y conectados con decisiones','Solo indicadores de ventas','Cambiar fórmulas cada semana','B','Un tablero ejecutivo prioriza estabilidad, definición y accionabilidad.'),
(10,'Si mejora el tiempo de respuesta pero empeora la calidad del diagnóstico, BALIZA recomienda:','Premiar únicamente la velocidad','Ignorar ambas métricas','Leer la tensión entre indicadores e investigar antes de intervenir','Eliminar el KPI de calidad','C','El balance evita optimizar una métrica a costa del sistema.'),
(11,'¿Para qué sirve documentar fórmula y fuente de cada KPI?','Para aumentar burocracia','Para asegurar comparabilidad, trazabilidad y una interpretación común','Para impedir cambios para siempre','Para ocultar supuestos','B','Sin definición y fuente estables, las variaciones pueden ser artefactos y no cambios reales.'),
(12,'¿Qué debe ocurrir cuando un KPI cruza un umbral interno?','Aplicar una sanción automática','Prometer una corrección al cliente','Activar la zona de decisión definida: observar, investigar, intervenir o escalar según evidencia','Cambiar el umbral para que vuelva a verde','C','Los umbrales son señales de atención y deben conducir a una respuesta proporcional basada en evidencia.')
on conflict (position) do update set
  prompt=excluded.prompt,option_a=excluded.option_a,option_b=excluded.option_b,option_c=excluded.option_c,option_d=excluded.option_d,correct_option=excluded.correct_option,explanation=excluded.explanation;
