-- Compás Academy · Nivel 5 · Dirección Comercial Avanzada
-- Módulo 4: Liderazgo de supervisores y sistema de gestión. Curso permanece draft.

do $m$
declare
  v_course uuid; v_module uuid; jl jsonb;
  lessons jsonb := $c$[
    {"p":1,"t":"Dirigir líderes: del control individual al sistema de supervisión","d":"Rediseña el rol del director para dirigir supervisores mediante resultados, contexto, límites de decisión y cadencias, evitando microgestionar a los agentes.","m":43,"html":"<h2>Objetivo</h2><p>Pasar de resolver el trabajo de cada agente a construir un sistema donde los supervisores puedan dirigir con autonomía verificable.</p><h3>Marco ORBITA</h3><p><strong>O</strong>bjetivo: resultado y estándar común. <strong>R</strong>ol: quién decide, ejecuta y escala. <strong>B</strong>orde: límites de autoridad, riesgo y recursos. <strong>I</strong>ndicador: evidencia que permite revisar sin microgestionar. <strong>T</strong>iempo: cadencia de seguimiento proporcional. <strong>A</strong>prendizaje: decisión, resultado y ajuste que vuelve al sistema.</p><h3>Contenido</h3><p>Al dirigir supervisores, el director deja de ser el punto de aprobación de cada conversación comercial. Su responsabilidad es diseñar claridad: resultados esperados, decisiones delegables, excepciones que requieren escalamiento y señales que permiten detectar deterioro. El span of control no se define por un número universal; depende de complejidad, madurez de los líderes, variabilidad del trabajo y carga de coordinación. Cuando el director interviene directamente en cada caso, puede mejorar una situación puntual pero debilita la capacidad del supervisor y crea dependencia.</p><h3>Caso</h3><p>Dos supervisores consultan al director cada descuento, reasignación y conflicto de prioridad. ORBITA separa decisiones rutinarias con límites documentados de excepciones de alto impacto. El director deja de responder casos repetitivos y revisa patrones, calidad y excepciones.</p><h3>Ejercicio</h3><p>Mapea diez decisiones frecuentes del equipo. Clasifica cuáles pertenecen al agente, supervisor o director; define borde de autoridad, evidencia requerida y condición de escalamiento para cada una.</p><h3>Material para plataforma</h3><p>Plantilla ORBITA: objetivo, rol responsable, decisiones delegadas, límites, KPI/evidencia, cadencia, excepciones y aprendizaje registrado.</p><h3>Registro en Compás One</h3><p>Documenta responsable, decisión, límite de autoridad, excepción, evidencia y fecha de revisión. Los permisos reales del producto deben respetar el rol asignado; este ejercicio no concede permisos por sí mismo.</p><h3>Guion de video</h3><p>Apertura: dirigir supervisores no es supervisar más personas. Desarrollo: muestra cómo un director se convierte en cuello de botella al aprobar todo y cómo ORBITA redistribuye decisiones con límites. Cierre: el director escala liderazgo cuando diseña autonomía con evidencia.</p>"},
    {"p":2,"t":"Calibración de supervisores y revisión de desempeño de equipos","d":"Crea una lectura comparable entre equipos sin borrar contexto, detectando diferencias de criterio, calidad, capacidad y ejecución antes de intervenir.","m":44,"html":"<h2>Objetivo</h2><p>Comparar equipos y supervisores con criterios consistentes para distinguir variación explicable de una brecha de gestión.</p><h3>Marco CALIBRA</h3><p><strong>C</strong>riterio: definición común del estándar. <strong>A</strong>lcance: segmento, periodo y población comparables. <strong>L</strong>ectura: resultado y señales adelantadas. <strong>I</strong>nconsistencia: diferencia de criterio, dato o ejecución. <strong>B</strong>recha: magnitud e impacto verificable. <strong>R</strong>espuesta: coaching, ajuste de proceso, recurso o escalamiento. <strong>A</strong>prendizaje: comprobar efecto y actualizar el estándar cuando corresponda.</p><h3>Contenido</h3><p>Calibrar no significa obligar a todos los equipos a producir la misma cifra. Significa usar definiciones comunes y después explicar diferencias por mezcla de cartera, capacidad, madurez, canal, territorio o ejecución. Una revisión ejecutiva debe observar resultados, calidad, permanencia, carga y disciplina de proceso. Los rankings aislados pueden castigar contextos distintos o premiar atajos. La conversación de calibración busca una interpretación compartida y una acción concreta.</p><h3>Caso</h3><p>Un supervisor tiene mayor conversión que otro, pero atiende una cartera más madura y presenta mayor retrabajo posterior. CALIBRA evita declarar un ganador; normaliza alcance, incorpora calidad y descubre que parte de la diferencia proviene del segmento y otra parte de un criterio de calificación inconsistente.</p><h3>Ejercicio</h3><p>Compara dos equipos usando cinco indicadores y tres variables de contexto. Identifica qué diferencias requieren normalización, cuáles son brechas reales y qué acción corresponde al director.</p><h3>Material para plataforma</h3><p>Matriz CALIBRA con definición, periodo, segmento, KPI, contexto, brecha observada, hipótesis, evidencia adicional, intervención y fecha de comprobación.</p><h3>Registro en Compás One</h3><p>Registra definiciones de KPI, filtros de comparación, excepciones, evidencia y acuerdos de calibración. No completes datos faltantes con promedios inventados.</p><h3>Guion de video</h3><p>Apertura: comparar equipos sin contexto puede producir una mala decisión. Desarrollo: presenta dos supervisores con conversiones distintas y añade cartera y calidad hasta cambiar la interpretación. Explica CALIBRA. Cierre: calibrar es hacer comparable el criterio antes de juzgar el resultado.</p>"},
    {"p":3,"t":"Desarrollo de supervisores y sistema de gestión de liderazgo","d":"Convierte las reuniones de dirección en un sistema para desarrollar criterio, delegar decisiones y elevar la capacidad de los supervisores sin sustituirlos.","m":45,"html":"<h2>Objetivo</h2><p>Construir una cadencia de gestión que desarrolle supervisores capaces de diagnosticar, decidir, ejecutar y aprender.</p><h3>Marco ELEVA</h3><p><strong>E</strong>videncia: qué está ocurriendo y con qué calidad de dato. <strong>L</strong>ectura del líder: diagnóstico del supervisor antes de recibir la respuesta del director. <strong>E</strong>lección: decisión propuesta y alternativas. <strong>V</strong>erificación: resultado esperado, riesgo, checkpoint y evidencia. <strong>A</strong>prendizaje: retrospectiva que aumenta el criterio para la siguiente decisión.</p><h3>Contenido</h3><p>Una reunión de dirección no debe convertirse en una lista de casos para que el director resuelva. El supervisor llega con evidencia, diagnóstico y propuesta. El director prueba el razonamiento, añade contexto, protege límites y decide solo cuando la autoridad o el riesgo lo requieren. La cadencia puede combinar revisión semanal de operación, 1:1 de liderazgo y calibración periódica; su frecuencia debe responder a riesgo y madurez, no a una regla arbitraria. El desarrollo se observa cuando el supervisor necesita menos instrucciones para decisiones equivalentes y mejora la calidad de su diagnóstico.</p><h3>Caso</h3><p>Una supervisora escala cada semana oportunidades estancadas esperando que el director indique qué hacer. Con ELEVA debe presentar patrón, evidencia, hipótesis, decisión propuesta y criterio de éxito. Tras varias revisiones, resuelve casos equivalentes dentro de sus límites y escala únicamente excepciones.</p><h3>Ejercicio</h3><p>Diseña una agenda de 30 minutos para revisión de liderazgo: evidencia, diagnóstico del supervisor, decisión propuesta, riesgo, checkpoint y aprendizaje. Simula dos rondas y elimina cualquier punto que convierta al director en operador del caso.</p><h3>Material para plataforma</h3><p>Ficha ELEVA para 1:1 de liderazgo y revisión ejecutiva: evidencia, lectura, alternativas, decisión, autoridad, riesgo, checkpoint, resultado y aprendizaje.</p><h3>Registro en Compás One</h3><p>Conserva acuerdos, responsables, checkpoints y evidencia de resultado sin registrar información personal innecesaria. El historial sirve para aprendizaje y trazabilidad, no para fabricar evaluaciones o ascensos automáticos.</p><h3>Guion de video</h3><p>Apertura: si el supervisor trae problemas y el director siempre trae respuestas, el sistema no está desarrollando líderes. Desarrollo: transforma una reunión de casos en una conversación ELEVA. Cierre: el objetivo no es que el supervisor pregunte menos, sino que piense y decida mejor dentro de límites claros.</p>"}
  ]$c$::jsonb;
begin
  select id into v_course from public.courses where slug='nivel-5-direccion-comercial-avanzada-compas' limit 1;
  if v_course is null then raise exception 'Nivel 5 course is required before Module 4'; end if;
  select id into v_module from public.modules where course_id=v_course and position=4 limit 1;
  if v_module is null then
    insert into public.modules(course_id,title,description,position)
    values(v_course,'4. Liderazgo de supervisores y sistema de gestión','Dirección de líderes, calibración entre equipos, delegación de decisiones y desarrollo del criterio supervisor.',4)
    returning id into v_module;
  else
    update public.modules set title='4. Liderazgo de supervisores y sistema de gestión',description='Dirección de líderes, calibración entre equipos, delegación de decisiones y desarrollo del criterio supervisor.' where id=v_module;
  end if;
  for jl in select value from jsonb_array_elements(lessons) loop
    if exists(select 1 from public.lessons where module_id=v_module and position=(jl->>'p')::int) then
      update public.lessons set title=jl->>'t',description=jl->>'d',lesson_type='text',content_html=jl->>'html',duration_minutes=(jl->>'m')::int,is_preview=false,updated_at=now() where module_id=v_module and position=(jl->>'p')::int;
    else
      insert into public.lessons(module_id,title,description,lesson_type,content_html,duration_minutes,position,is_preview)
      values(v_module,jl->>'t',jl->>'d','text',jl->>'html',(jl->>'m')::int,(jl->>'p')::int,false);
    end if;
  end loop;
end $m$;
