-- Compás Academy · Nivel 5 · Módulo 4 · Evaluación formativa
-- 12 reactivos, aprobación 80% (mínimo 10/12).

create table if not exists public.freelance_level5_module4_assessment (
  id bigint generated by default as identity primary key,
  position integer not null unique,
  prompt text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option char(1) not null check (correct_option in ('A','B','C','D')),
  explanation text not null,
  created_at timestamptz not null default now()
);

alter table public.freelance_level5_module4_assessment enable row level security;
revoke all on public.freelance_level5_module4_assessment from public,anon,authenticated;
grant all on public.freelance_level5_module4_assessment to service_role;

insert into public.freelance_level5_module4_assessment(position,prompt,option_a,option_b,option_c,option_d,correct_option,explanation) values
(1,'¿Cuál es el cambio principal al pasar de supervisar agentes a dirigir supervisores?','Resolver más casos personalmente','Diseñar objetivos, límites, evidencia y cadencias para que los líderes decidan con autonomía verificable','Eliminar las revisiones de desempeño','Delegar toda decisión sin límites','B','La dirección de líderes crea un sistema de autonomía con control por evidencia, no microgestión.'),
(2,'En ORBITA, ¿para qué sirve definir el borde de una decisión?','Para impedir que el supervisor decida','Para establecer límites de autoridad, riesgo y recursos y saber cuándo escalar','Para sustituir los KPIs','Para asignar ventas ficticias','B','El borde permite delegar decisiones rutinarias sin perder control sobre excepciones relevantes.'),
(3,'¿Qué determina un span of control saludable?','Un número universal de personas','Solo la antigüedad del director','Complejidad, madurez de los líderes, variabilidad del trabajo y carga de coordinación','El tamaño de la oficina','C','La capacidad de dirección depende del contexto del sistema y no de una cifra fija aplicable a todos.'),
(4,'Si un director aprueba personalmente cada descuento y reasignación rutinaria, ¿qué riesgo aparece?','Mayor autonomía del supervisor','Dependencia y cuello de botella en la dirección','Mejor calibración automática','Menor necesidad de límites','B','Resolver cada caso puede debilitar el criterio del supervisor y concentrar innecesariamente las decisiones.'),
(5,'¿Qué significa calibrar supervisores correctamente?','Obligar a todos los equipos a producir exactamente el mismo resultado','Comparar con criterios y alcances consistentes y explicar diferencias de contexto antes de intervenir','Crear un ranking sin contexto','Usar únicamente la conversión','B','CALIBRA busca comparabilidad del criterio y distingue contexto de brechas reales de gestión.'),
(6,'Un equipo convierte más, pero atiende una cartera más madura y genera más retrabajo. ¿Cuál es la lectura adecuada?','Declararlo automáticamente el mejor equipo','Ignorar la conversión','Normalizar contexto e incorporar calidad antes de atribuir la diferencia al supervisor','Sancionar al otro supervisor','C','La conversión aislada no permite atribuir desempeño sin considerar mezcla y calidad.'),
(7,'¿Por qué una definición común de KPI es necesaria en una calibración?','Porque elimina toda diferencia entre equipos','Porque permite saber si las variaciones representan desempeño y no criterios de medición distintos','Porque garantiza la meta','Porque evita revisar contexto','B','Sin definiciones comparables, la diferencia observada puede ser un artefacto de medición.'),
(8,'En CALIBRA, después de identificar una brecha verificable, ¿qué sigue?','Aplicar siempre una sanción','Elegir una respuesta proporcional como coaching, proceso, recurso o escalamiento y comprobar su efecto','Cambiar el KPI','Ocultar la diferencia','B','La respuesta depende de la causa y debe verificarse posteriormente.'),
(9,'En una reunión ELEVA, ¿qué debe presentar primero el supervisor ante un problema recurrente?','Una solicitud para que el director lo resuelva','Evidencia, su lectura del problema y una decisión propuesta','Solo el nombre del agente','Una promesa de resultado','B','El sistema desarrolla criterio cuando el supervisor diagnostica y propone antes de recibir la respuesta del director.'),
(10,'¿Qué señal indica desarrollo real del criterio de un supervisor?','Escala cada vez más casos equivalentes','Necesita menos instrucciones para decisiones equivalentes y mejora la calidad de su diagnóstico','Deja de documentar decisiones','Recibe permisos superiores automáticamente','B','El desarrollo se observa en autonomía y calidad de razonamiento dentro de los límites del rol.'),
(11,'¿Cómo debe definirse la frecuencia de revisión de liderazgo?','Siempre diaria','Siempre mensual','Según riesgo, complejidad y madurez, con una cadencia proporcional','Sin ninguna cadencia','C','La frecuencia útil responde al riesgo y a la autonomía disponible, no a una regla arbitraria.'),
(12,'¿Qué NO debe producir automáticamente el historial de reuniones y desempeño?','Aprendizaje y trazabilidad','Checkpoints de seguimiento','Ascensos, permisos o certificaciones sin el proceso formal correspondiente','Evidencia para revisar decisiones','C','El historial apoya gestión y aprendizaje, pero no sustituye reglas formales de carrera, permisos o certificación.')
on conflict (position) do update set
  prompt=excluded.prompt,option_a=excluded.option_a,option_b=excluded.option_b,option_c=excluded.option_c,option_d=excluded.option_d,correct_option=excluded.correct_option,explanation=excluded.explanation;
