-- Compás Academy · Nivel 5 · Módulo 5 · Expansión comercial, diseño organizacional y gestión del cambio
-- 3 clases / 134 minutos. Curso permanece draft.

DO $$
DECLARE
  v_course uuid;
  v_module uuid;
BEGIN
  SELECT id INTO v_course FROM public.courses WHERE slug='nivel-5-direccion-comercial-avanzada-compas' LIMIT 1;
  IF v_course IS NULL THEN RAISE EXCEPTION 'Curso Nivel 5 no encontrado'; END IF;

  INSERT INTO public.modules(course_id,title,position)
  VALUES(v_course,'Módulo 5 · Expansión comercial, diseño organizacional y gestión del cambio',5)
  ON CONFLICT (course_id,position) DO UPDATE SET title=excluded.title
  RETURNING id INTO v_module;

  INSERT INTO public.lessons(module_id,title,position,duration_minutes,content_html) VALUES
  (v_module,'Clase 1 · Cuándo expandir: readiness antes de abrir una nueva célula',1,44,
  '<h2>Objetivo</h2><p>Determinar si el sistema comercial está listo para crecer sin confundir demanda con capacidad de expansión.</p><h2>Marco EXPANDE</h2><p><strong>E</strong>videncia de demanda; <strong>X</strong> capacidad excedente o cuello de botella comprobado; <strong>P</strong>roceso repetible; <strong>A</strong>utonomía de liderazgo; <strong>N</strong>úmeros sostenibles; <strong>D</strong>ependencias críticas; <strong>E</strong>xperimento controlado.</p><h2>Contenido</h2><p>La expansión responsable requiere evidencia de demanda, proceso estable, capacidad de supervisión, economía viable y riesgos identificados. Abrir una célula no corrige por sí misma un proceso defectuoso. Se define hipótesis, alcance, límite de inversión, indicadores adelantados y criterio de detener/continuar antes de escalar.</p><h2>Caso</h2><p>Un equipo tiene más leads de los que puede atender, pero el retrabajo es alto y el supervisor decide casi todos los casos. EXPANDE indica estabilizar calidad y autonomía antes de duplicar estructura.</p><h2>Ejercicio</h2><p>Completa una matriz EXPANDE para una expansión hipotética y clasifica cada dimensión como evidencia suficiente, incertidumbre o bloqueo. No inventes métricas faltantes.</p><h2>Material para plataforma</h2><p>Plantilla Readiness de Expansión: hipótesis, demanda, capacidad, proceso, liderazgo, economía, dependencias, experimento y criterio de salida.</p><h2>Aplicación en Compás One</h2><p>Registrar la iniciativa como proyecto de expansión con responsables, evidencia, checkpoints y riesgos; no crear ventas ni proyecciones ficticias.</p><h2>Guion de video</h2><p>Explica por qué crecer antes de estar listo amplifica problemas. Recorre EXPANDE, presenta el caso y cierra mostrando cómo un experimento pequeño protege operación y cliente.</p>'),
  (v_module,'Clase 2 · Diseño organizacional: células, responsabilidades y nuevos supervisores',2,45,
  '<h2>Objetivo</h2><p>Diseñar una estructura que distribuya responsabilidad sin duplicar funciones ni crear zonas grises.</p><h2>Marco CELULA</h2><p><strong>C</strong>liente/resultado; <strong>E</strong>ntregables; <strong>L</strong>ímites; <strong>U</strong>n dueño; <strong>L</strong>azos con otras áreas; <strong>A</strong>utoridad.</p><h2>Contenido</h2><p>La estructura sigue al flujo de valor. Cada célula necesita un resultado claro, un responsable, límites de decisión, capacidad definida y handoffs explícitos. El span of control depende de complejidad y madurez, no de una cifra universal. Un nuevo supervisor requiere criterios de readiness, acompañamiento y autoridad gradual; preparación no equivale a ascenso automático.</p><h2>Caso</h2><p>Dos supervisores creen ser responsables de la misma cartera y ninguno asume el seguimiento de excepciones. CELULA redefine dueño, entregable, autoridad y punto de transferencia.</p><h2>Ejercicio</h2><p>Diseña una célula comercial en una hoja: resultado, roles, decisiones autónomas, decisiones escalables, interfaces y capacidad. Identifica al menos dos riesgos de solapamiento.</p><h2>Material para plataforma</h2><p>Canvas CELULA y matriz de decisiones: decide, consulta, informa, escala.</p><h2>Aplicación en Compás One</h2><p>Representar responsables, equipos y handoffs mediante campos/etapas existentes; cualquier cambio de permisos debe seguir el proceso formal del producto.</p><h2>Guion de video</h2><p>Parte de un organigrama confuso y conviértelo en flujo de responsabilidad. Explica CELULA y demuestra cómo autoridad y límites reducen microgestión.</p>'),
  (v_module,'Clase 3 · Gestión del cambio y control de riesgo durante la expansión',3,45,
  '<h2>Objetivo</h2><p>Implementar cambios comerciales de forma progresiva, medible y reversible cuando el riesgo lo requiera.</p><h2>Marco CAMBIA</h2><p><strong>C</strong>aso para cambiar; <strong>A</strong>fectados; <strong>M</strong>ínimo cambio viable; <strong>B</strong>arreras y riesgos; <strong>I</strong>ndicadores y escucha; <strong>A</strong>juste, adopción o reversa.</p><h2>Contenido</h2><p>El cambio falla cuando se comunica como anuncio y no como transición operativa. Se identifica quién cambia conducta, qué soporte necesita, qué se mantiene, cómo se mide adopción y qué señales obligan a ajustar. La expansión usa pilotos, ventanas de revisión y mecanismos de rollback cuando sean aplicables.</p><h2>Caso</h2><p>Una nueva asignación de leads reduce tiempos en un equipo pero aumenta reasignaciones y dudas en otro. CAMBIA obliga a observar adopción y calidad antes de desplegarla globalmente.</p><h2>Ejercicio</h2><p>Construye un plan CAMBIA para introducir una nueva célula: afectados, conducta esperada, piloto, soporte, indicadores, riesgos y criterio de reversa.</p><h2>Material para plataforma</h2><p>Checklist de cambio: propósito, afectados, entrenamiento, piloto, comunicación, indicadores, feedback, decisión y retrospectiva.</p><h2>Aplicación en Compás One</h2><p>Documentar cambios, responsables, incidencias y evidencia de adopción. No elevar permisos ni alterar reglas de carrera automáticamente.</p><h2>Guion de video</h2><p>Contrasta un lanzamiento abrupto con un cambio pilotado. Recorre CAMBIA y cierra con la idea de que escalar es aprender con límites, no desplegar más rápido.</p>')
  ON CONFLICT (module_id,position) DO UPDATE SET title=excluded.title,duration_minutes=excluded.duration_minutes,content_html=excluded.content_html;

  UPDATE public.courses SET status='draft' WHERE id=v_course;
END $$;