-- Compás Academy · Nivel 5 · Módulo 6 · Dirección de portafolio, prioridades estratégicas y continuidad del negocio
-- 3 clases / 137 minutos. Curso permanece draft.

DO $$
DECLARE
  v_course uuid;
  v_module uuid;
BEGIN
  SELECT id INTO v_course FROM public.courses WHERE slug='nivel-5-direccion-comercial-avanzada-compas' LIMIT 1;
  IF v_course IS NULL THEN RAISE EXCEPTION 'Curso Nivel 5 no encontrado'; END IF;

  INSERT INTO public.modules(course_id,title,position)
  VALUES(v_course,'Módulo 6 · Dirección de portafolio, prioridades estratégicas y continuidad del negocio',6)
  ON CONFLICT (course_id,position) DO UPDATE SET title=excluded.title
  RETURNING id INTO v_module;

  INSERT INTO public.lessons(module_id,title,position,duration_minutes,content_html) VALUES
  (v_module,'Clase 1 · Portafolio estratégico: elegir, secuenciar y detener iniciativas',1,45,
  '<h2>Objetivo</h2><p>Dirigir un portafolio comercial limitado por capacidad, priorizando iniciativas por valor, evidencia, urgencia y riesgo en lugar de acumular proyectos.</p><h2>Marco CARTERA</h2><p><strong>C</strong>ontribución estratégica; <strong>A</strong>lineación con el cliente; <strong>R</strong>etorno o aprendizaje esperado; <strong>T</strong>iempo y capacidad requerida; <strong>E</strong>videncia disponible; <strong>R</strong>iesgo y dependencias; <strong>A</strong>cción: iniciar, mantener, pausar o detener.</p><h2>Contenido de clase</h2><p>Una dirección madura no intenta ejecutar todas las oportunidades. Distingue operación obligatoria, crecimiento, experimentación y deuda/riesgo. Cada iniciativa compite por atención, capacidad y capital. CARTERA obliga a explicitar la hipótesis, el resultado esperado, la evidencia existente, el costo de oportunidad y la condición de salida. Una prioridad sin renuncia no es prioridad. Los proyectos con evidencia insuficiente pueden convertirse en experimentos pequeños; los que consumen capacidad sin aprendizaje ni contribución deben pausarse o detenerse.</p><h2>Caso</h2><p>La dirección tiene cinco iniciativas simultáneas: nuevo canal, expansión regional, automatización, recuperación de cartera y capacitación. La capacidad solo permite ejecutar tres con calidad. CARTERA muestra que recuperación es obligatoria por riesgo, automatización libera capacidad y el nuevo canal puede probarse como experimento; la expansión se difiere hasta resolver dependencias.</p><h2>Ejercicio</h2><p>Construye una cartera de seis iniciativas hipotéticas. Clasifica contribución, evidencia, capacidad, dependencia y riesgo. Elige máximo tres activas y documenta qué se pausa y por qué. No inventes retornos que no estén disponibles.</p><h2>Material para plataforma</h2><p>Matriz CARTERA: iniciativa, categoría, hipótesis, evidencia, valor/aprendizaje, capacidad, riesgo, dependencias, dueño, checkpoint y decisión.</p><h2>Aplicación en Compás One</h2><p>Registrar iniciativas y checkpoints con responsables y evidencia. El tablero debe distinguir datos reales, supuestos y pendientes; no crear ventas, ROI o forecasts ficticios.</p><h2>Guion de video</h2><p>Abre con una dirección saturada de proyectos. Explica que estrategia también es decidir qué no hacer. Recorre CARTERA con el caso, muestra cómo secuenciar y cierra con la regla: toda iniciativa activa debe tener dueño, evidencia, capacidad y condición de revisión.</p>'),
  (v_module,'Clase 2 · Prioridades estratégicas y reasignación de recursos bajo incertidumbre',2,46,
  '<h2>Objetivo</h2><p>Reasignar capacidad y recursos cuando cambia la evidencia sin caer en cambios impulsivos ni sostener planes obsoletos.</p><h2>Marco PRIORIZA</h2><p><strong>P</strong>ropósito; <strong>R</strong>esultado observable; <strong>I</strong>ndicadores adelantados; <strong>O</strong>pciones; <strong>R</strong>estricciones; <strong>I</strong>ncertidumbre; <strong>Z</strong>ona de decisión; <strong>A</strong>juste y registro.</p><h2>Contenido de clase</h2><p>Priorizar no significa reaccionar a cada variación. Se establecen ventanas de decisión y umbrales para distinguir ruido de cambio material. Los recursos se reasignan cuando nueva evidencia modifica el valor esperado, el riesgo, la urgencia o la capacidad disponible. PRIORIZA separa hechos de supuestos, conserva trazabilidad y evita el sesgo de costo hundido. La dirección protege primero compromisos críticos, experiencia del cliente, seguridad y continuidad; después distribuye capacidad hacia crecimiento y experimentos.</p><h2>Caso</h2><p>Un canal nuevo consume más atención de la prevista mientras una cartera existente muestra deterioro en seguimiento. En vez de añadir personas sin diagnóstico, la dirección revisa restricciones y señales, reduce temporalmente el experimento y reasigna capacidad al riesgo comprobado.</p><h2>Ejercicio</h2><p>Recibe cuatro cambios de escenario: caída de capacidad, incremento de demanda, deterioro de calidad y oportunidad de canal. Para cada uno decide mantener, acelerar, reducir o pausar iniciativas y registra evidencia y umbral que justifican la decisión.</p><h2>Material para plataforma</h2><p>Hoja PRIORIZA y bitácora de reasignación: antes, señal, decisión, recurso movido, impacto esperado, fecha de revisión y responsable.</p><h2>Aplicación en Compás One</h2><p>Usar KPIs y proyectos para registrar decisiones y responsables. Las recomendaciones del agente inteligente deben citar los indicadores disponibles y marcar incertidumbre cuando falten datos.</p><h2>Guion de video</h2><p>Presenta la diferencia entre disciplina y rigidez. Explica PRIORIZA, el sesgo de costo hundido y los umbrales de decisión. Cierra mostrando una reasignación reversible y trazable.</p>'),
  (v_module,'Clase 3 · Continuidad comercial: operar, responder y recuperar ante disrupciones',3,46,
  '<h2>Objetivo</h2><p>Diseñar continuidad comercial para sostener funciones críticas, proteger información y recuperar operación ante fallas o ausencias relevantes.</p><h2>Marco CONTINUA</h2><p><strong>C</strong>ríticos: procesos y activos; <strong>O</strong>wners y suplentes; <strong>N</strong>iveles mínimos de servicio interno; <strong>T</strong>riggers de contingencia; <strong>I</strong>nformación y accesos protegidos; <strong>N</strong>avegación de la respuesta; <strong>U</strong>nidad de recuperación; <strong>A</strong>prendizaje posterior.</p><h2>Contenido de clase</h2><p>Continuidad no es predecir cada incidente sino preparar capacidades mínimas. Se identifican procesos críticos, dependencias, responsables y suplentes; se documenta cómo activar contingencia, qué decisiones pueden tomarse y cómo recuperar el servicio. Los accesos siguen mínimo privilegio: un plan de continuidad no justifica compartir credenciales ni elevar permisos preventivamente. La recuperación termina con retrospectiva y acciones preventivas verificables.</p><h2>Caso</h2><p>Un supervisor clave queda indisponible durante una campaña activa. El equipo tiene información operativa pero varias excepciones dependían de su criterio. CONTINUA activa suplencia previamente definida, prioriza compromisos críticos, escala decisiones fuera de autoridad y registra lo aprendido para reducir dependencia futura.</p><h2>Ejercicio</h2><p>Diseña un plan CONTINUA para una interrupción hipotética: tres funciones críticas, responsables/suplentes, dependencia, trigger, operación mínima, comunicación, escalamiento, recuperación y retrospectiva. No incluyas contraseñas ni datos sensibles.</p><h2>Material para plataforma</h2><p>Canvas CONTINUA: proceso crítico, impacto, dependencia, owner, suplente, mínimo operativo, trigger, canal de coordinación, autoridad, recuperación y aprendizaje.</p><h2>Aplicación en Compás One</h2><p>Documentar responsables, incidencias y tareas de recuperación con permisos existentes. Cualquier elevación de acceso debe seguir el flujo formal y auditable del producto.</p><h2>Guion de video</h2><p>Abre con una ausencia inesperada que bloquea decisiones. Recorre CONTINUA, destaca mínimo privilegio y suplencia preparada, y termina mostrando que la continuidad madura reduce dependencia de personas sin eliminar controles.</p>')
  ON CONFLICT (module_id,position) DO UPDATE SET title=excluded.title,duration_minutes=excluded.duration_minutes,content_html=excluded.content_html;

  UPDATE public.courses SET status='draft' WHERE id=v_course;
END $$;