(() => {
  const svg = {
    home:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10.5 12 3l9 7.5"/><path d="M5.5 9.5V20h13V9.5"/></svg>`,
    courses:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="5" width="6.5" height="6.5" rx="1.4"/><rect x="13.5" y="5" width="6.5" height="6.5" rx="1.4"/><rect x="4" y="13.5" width="6.5" height="6.5" rx="1.4"/><path d="M14 14h6m-6 3h6m-6 3h4"/></svg>`,
    resources:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M6 4h9l5 5v11a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/><path d="M15 4v5h5"/></svg>`,
    agenda:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/><path d="M8.5 14h.01M12 14h.01M15.5 14h.01M8.5 17h.01M12 17h.01"/></svg>`,
    certificates:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M7 3h10v7a5 5 0 1 1-10 0V3Z"/><path d="m9 14-1.5 7L12 19l4.5 2-1.5-7"/></svg>`,
    help:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.6 2.6 0 1 1 4.5 1.8c-.8.8-1.5 1.2-1.5 2.2"/><path d="M12 17h.01"/></svg>`,
    profile:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="4"/><path d="M4 20a8 8 0 0 1 16 0"/></svg>`,
    explore:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="8"/><path d="m15.5 8.5-2.8 5.7-4.2 1.3 1.3-4.2 5.7-2.8Z"/></svg>`,
    admin:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1 1 0 0 0 .2 1.1l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1 1 0 0 0-1.1-.2 1 1 0 0 0-.6.9V20a2 2 0 1 1-4 0v-.2a1 1 0 0 0-.7-.9 1 1 0 0 0-1.1.2l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1 1 0 0 0 .2-1.1 1 1 0 0 0-.9-.6H4a2 2 0 1 1 0-4h.2a1 1 0 0 0 .9-.7 1 1 0 0 0-.2-1.1l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1 1 0 0 0 1.1.2 1 1 0 0 0 .6-.9V4a2 2 0 1 1 4 0v.2a1 1 0 0 0 .7.9 1 1 0 0 0 1.1-.2l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1 1 0 0 0-.2 1.1 1 1 0 0 0 .9.6H20a2 2 0 1 1 0 4h-.2a1 1 0 0 0-.4.6Z"/></svg>`,
    install:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v11"/><path d="m8 10 4 4 4-4"/><path d="M5 21h14"/></svg>`,
    bell:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M6 8a6 6 0 1 1 12 0c0 7 3 7 3 9H3c0-2 3-2 3-9"/><path d="M10 20a2 2 0 0 0 4 0"/></svg>`,
    refresh:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M20 11a8 8 0 1 0 2 5.3"/><path d="M20 4v7h-7"/></svg>`,
    play:`<svg viewBox="0 0 24 24" fill="currentColor"><path d="m9 7 9 5-9 5V7Z"/></svg>`,
    layer:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="m12 3 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5"/><path d="m3 16 9 5 9-5"/></svg>`,
    chart:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19h16"/><path d="M7 16V9"/><path d="M12 16V5"/><path d="M17 16v-4"/></svg>`,
    shield:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3 5 6v5c0 5 3.5 8.5 7 10 3.5-1.5 7-5 7-10V6l-7-3Z"/><path d="m9.5 12 1.7 1.7 3.5-3.8"/></svg>`
  };
  const iconByLabel={Inicio:'home','Mis cursos':'courses','Mi biblioteca':'resources',Calendario:'agenda',Certificados:'certificates',Ayuda:'help','Mi perfil':'profile','Explorar cursos':'explore',Administrar:'admin','Mis contenidos':'admin'};
  const renderSVG=name=>svg[name]||svg.layer;
  function replaceNavIcons(root=document){
    root.querySelectorAll('.sidebar .nav-link').forEach(link=>{const label=link.textContent.replace(/\s+/g,' ').trim();const target=Object.keys(iconByLabel).find(key=>label.includes(key));const node=link.querySelector('.nav-icon');if(node&&!node.dataset.premiumDone){node.dataset.premiumDone='1';node.innerHTML=renderSVG(target?iconByLabel[target]:'layer')}});
    root.querySelectorAll('.mobile-nav button').forEach(button=>{const label=button.textContent.replace(/\s+/g,' ').trim();const target=Object.keys(iconByLabel).find(key=>label.includes(key));const first=button.querySelector('span');if(first&&!first.dataset.premiumDone){first.dataset.premiumDone='1';first.innerHTML=renderSVG(target?iconByLabel[target]:'layer')}});
  }
  function replaceTopbarIcons(root=document){root.querySelectorAll('.top-actions .icon-button').forEach(button=>{if(button.dataset.premiumDone)return;button.dataset.premiumDone='1';const title=(button.getAttribute('title')||'').toLowerCase();let icon='layer';if(title.includes('instalar'))icon='install';else if(title.includes('notificaciones'))icon='bell';else if(title.includes('ayuda'))icon='help';else if(title.includes('actualizar'))icon='refresh';const badge=button.querySelector('span');button.innerHTML=renderSVG(icon);if(badge)button.appendChild(badge)})}
  function decorateMetrics(root=document){[['.dashboard-summary article>span','chart'],['.workspace-summary-grid article>span','layer'],['.workspace-folder-icon','layer']].forEach(([selector,icon])=>root.querySelectorAll(selector).forEach(el=>{if(!el.dataset.premiumDone){el.dataset.premiumDone='1';el.innerHTML=renderSVG(icon)}}))}
  function filterCatalogByText(term){const query=(term||'').trim().toLowerCase();document.querySelectorAll('#public-program-grid .catalog-card').forEach(card=>{card.style.display=!query||card.textContent.toLowerCase().includes(query)?'':'none'})}
  function addPublicPremiumBlocks(root=document){
    const heroCopy=root.querySelector('.catalog-hero-copy');
    if(heroCopy&&!root.querySelector('.catalog-search-panel')){const panel=document.createElement('div');panel.className='catalog-search-panel';panel.innerHTML='<input class="catalog-search-input" type="search" placeholder="Buscar rutas, temas o herramientas" aria-label="Buscar rutas, temas o herramientas"><a class="btn btn-primary" href="#catalog/programs">Explorar Academy</a>';heroCopy.insertBefore(panel,heroCopy.querySelector('.catalog-trust'));panel.querySelector('input').addEventListener('input',e=>filterCatalogByText(e.target.value))}
    const section=root.querySelector('.public-section');const hero=root.querySelector('.academy-catalog-hero');
    if(hero&&!root.querySelector('.premium-top-strip')){const strip=document.createElement('section');strip.className='premium-top-strip';strip.innerHTML=`<article class="premium-market-tile"><span class="premium-icon-wrap">${renderSVG('play')}</span><div><strong>Aprendizaje práctico</strong><small>Rutas aplicadas a procesos reales de negocio.</small></div></article><article class="premium-market-tile"><span class="premium-icon-wrap">${renderSVG('chart')}</span><div><strong>Experiencia premium</strong><small>Interfaz clara, elegante y preparada para crecer.</small></div></article><article class="premium-market-tile"><span class="premium-icon-wrap">${renderSVG('shield')}</span><div><strong>Ecosistema Compás</strong><small>Biblioteca, certificados, agenda y administración.</small></div></article>`;hero.parentNode.insertBefore(strip,hero.nextSibling)}
    if(section&&!root.querySelector('.premium-stats-grid')){const stats=document.createElement('div');stats.className='premium-stats-grid';stats.innerHTML=`<article class="premium-stat"><span class="premium-icon-wrap">${renderSVG('courses')}</span><div><strong>6 rutas base</strong><small>Compás One, ventas, marketing, Meta Ads, IA y automatización.</small></div></article><article class="premium-stat"><span class="premium-icon-wrap">${renderSVG('resources')}</span><div><strong>Biblioteca privada</strong><small>Guías, descargas y recursos por ruta.</small></div></article><article class="premium-stat"><span class="premium-icon-wrap">${renderSVG('certificates')}</span><div><strong>Certificación y avance</strong><small>Seguimiento del progreso y constancias.</small></div></article>`;section.insertBefore(stats,section.querySelector('.catalog-filters'))}
  }
  function decorateCards(root=document){root.querySelectorAll('.catalog-card').forEach(card=>{if(card.dataset.enhancedPremium)return;card.dataset.enhancedPremium='1';const body=card.querySelector('.catalog-card-body');if(body&&!body.querySelector('.premium-card-meta')){const meta=document.createElement('div');meta.className='premium-card-meta';meta.innerHTML='<small class="card-meta">Experiencia premium · Aprende haciendo</small>';body.insertBefore(meta,body.querySelector('.catalog-actions, .coming-note')||null)}})}
  function run(root=document){document.body.classList.add('premium-ui-v8');replaceNavIcons(root);replaceTopbarIcons(root);decorateMetrics(root);addPublicPremiumBlocks(root);decorateCards(root)}
  const start=()=>{run();new MutationObserver(()=>run()).observe(document.body,{childList:true,subtree:true})};
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
})();