-- Nivel 4 · Módulo 6 — Desarrollo de talento, delegación y preparación de sucesores
-- Curso permanece draft. No crea alumnos, intentos ni certificados.

DO $$
DECLARE
  v_course uuid;
  v_module uuid;
BEGIN
  SELECT id INTO v_course FROM courses WHERE slug = 'nivel-4-liderazgo-supervision-comercial-compas' LIMIT 1;
  IF v_course IS NULL THEN RAISE EXCEPTION 'Nivel 4 no encontrado'; END IF;

  INSERT INTO modules (course_id, title, description, position)
  VALUES (v_course, 'Módulo 6 · Desarrollo de talento, delegación y preparación de sucesores',
    'Desarrolla capacidad en otras personas, delega con límites verificables y construye continuidad operativa sin otorgar ascensos automáticos.', 6)
  RETURNING id INTO v_module;

  INSERT INTO lessons (module_id, title, position, duration_minutes, content_html) VALUES
  (v_module, '6.1 · Detectar potencial y construir un plan de desarrollo', 1, 38,
   '<h2>Objetivo</h2><p>Distinguir desempeño actual, potencial y preparación antes de asignar responsabilidades mayores.</p><h2>Marco MAPA</h2><p><strong>M</strong>étrica observable; <strong>A</strong>ptitud demostrada; <strong>P</strong>ráctica deliberada; <strong>A</strong>utonomía comprobada.</p><h2>Contenido</h2><p>Un buen resultado aislado no prueba preparación para liderar. El supervisor reúne evidencia longitudinal, identifica fortalezas y brechas, acuerda una habilidad prioritaria y diseña una práctica con fecha y criterio de éxito. Potencial no equivale a promoción: toda decisión formal conserva las reglas de carrera vigentes.</p><h2>Caso</h2><p>Una agente supera su meta dos meses, pero sus registros son incompletos. MAPA reconoce su capacidad comercial y define como brecha la disciplina operativa antes de ampliar responsabilidad.</p><h2>Ejercicio</h2><p>Selecciona un perfil real sin datos sensibles. Registra una métrica, una aptitud demostrada, una práctica de 14 días y la evidencia que probará autonomía.</p><h2>Compás One</h2><p>Documenta la meta de desarrollo, actividad observable, fecha de revisión y evidencia. No registres diagnósticos personales ni información innecesaria.</p><h2>Guion de video</h2><p>Abre con: “Vender bien y estar listo para liderar son cosas distintas”. Explica MAPA, presenta el caso y cierra pidiendo una práctica observable.</p>'),
  (v_module, '6.2 · Delegar responsabilidad sin abandonar el control', 2, 39,
   '<h2>Objetivo</h2><p>Delegar resultados y decisiones dentro de límites claros, conservando trazabilidad y escalamiento.</p><h2>Marco DELEGA</h2><p><strong>D</strong>efine resultado; <strong>E</strong>stablece autoridad; <strong>L</strong>imita riesgos; <strong>E</strong>videncia esperada; <strong>G</strong>enera checkpoints; <strong>A</strong>justa o escala.</p><h2>Contenido</h2><p>Delegar no es repartir tareas ni desaparecer. Se define qué resultado se espera, qué puede decidir la persona, qué requiere autorización, qué evidencia entregará y cuándo se revisará. Los checkpoints disminuyen conforme aumenta la autonomía demostrada.</p><h2>Caso</h2><p>El supervisor delega la revisión semanal del pipeline. La persona puede ordenar prioridades y solicitar actualizaciones, pero descuentos, compensaciones y cambios de política siguen fuera de su autoridad.</p><h2>Ejercicio</h2><p>Diseña una delegación real con resultado, autoridad permitida, tres límites, evidencia y dos checkpoints.</p><h2>Compás One</h2><p>Asigna responsable, fecha, resultado esperado, dependencia y siguiente revisión. Evita duplicar información sensible en notas.</p><h2>Guion de video</h2><p>Contrasta “haz esto” con una delegación completa. Recorre DELEGA y muestra cómo los límites protegen tanto al equipo como al cliente.</p>'),
  (v_module, '6.3 · Preparar continuidad y sucesión responsable', 3, 39,
   '<h2>Objetivo</h2><p>Reducir dependencia de una sola persona mediante transferencia progresiva de conocimiento y pruebas de continuidad.</p><h2>Marco RELEVO</h2><p><strong>R</strong>oles críticos; <strong>E</strong>videncia del proceso; <strong>L</strong>ímites de autoridad; <strong>E</strong>nsayo acompañado; <strong>V</strong>alidación autónoma; <strong>O</strong>bservación posterior.</p><h2>Contenido</h2><p>La sucesión no promete un puesto. Identifica procesos críticos, documenta lo necesario, forma respaldo, realiza ensayo acompañado y luego una prueba autónoma con criterios definidos. La promoción formal, cuando corresponda, se evalúa por la ruta de carrera y requisitos vigentes.</p><h2>Caso</h2><p>Durante una ausencia programada, una agente preparada conduce la revisión del pipeline usando el mismo tablero, límites y escalamiento. El supervisor observa resultados y registra brechas sin otorgar un ascenso automático.</p><h2>Ejercicio</h2><p>Elige un proceso crítico y crea un plan RELEVO de cuatro semanas con evidencia de transferencia, ensayo y validación.</p><h2>Compás One</h2><p>Registra proceso, respaldo, checklist, prueba, incidencias y aprendizaje. Conserva permisos de sistema según rol real.</p><h2>Guion de video</h2><p>Abre con el riesgo de que “todo dependa de una persona”. Explica RELEVO y termina diferenciando continuidad operativa de promoción laboral.</p>');
END $$;
